import type { CandidateProfileSnapshotV2 } from '../src/profileV2';
export function emptySnapshot(): CandidateProfileSnapshotV2 {
  return {
    schemaVersion: 2,
    revision: '0',
    deletionEpoch: '0',
    hasStoredProfile: false,
    updatedAt: null,
    profile: {
      identity: {
        firstName: null,
        middleName: null,
        lastName: null,
        fullName: null,
        preferredName: null,
        pronouns: null,
      },
      contact: {
        email: null,
        phone: { countryCode: null, e164: null, display: null, type: null },
      },
      address: {
        line1: null,
        line2: null,
        city: null,
        region: null,
        postalCode: null,
        countryCode: null,
      },
      summary: null,
      noExperience: null,
      links: [],
      primaryLinkIdByKind: {
        LINKEDIN: null,
        GITHUB: null,
        PORTFOLIO: null,
        WEBSITE: null,
        OTHER: null,
        TWITTER: null,
      },
      experiences: [],
      primaryCurrentExperienceId: null,
      educations: [],
      skills: [],
      languages: [],
      projects: [],
      achievements: [],
      referrals: [],
      legacyUnresolved: { profileLocation: null, experienceLocations: [], fieldValues: [] },
      availability: { earliestStartDate: null, noticePeriodDays: null },
      referralSource: null,
      compensation: { expectedSalaryAmount: null, expectedSalaryCurrency: null, expectedSalaryPeriod: null },
      preferences: { workModes: null, openToRelocation: null, openToRelocationCities: null, contactCurrentEmployer: null, travelPercentMax: null },
      eligibility: { over18: null },
      workAuthorizations: [],
      scalarAuthorityByPath: {},
      referenceAuthority: { primaryLinkIdByKind: {}, primaryCurrentExperienceId: null },
    },
  };
}
