import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {DailyPlanController} from '../src/daily-plans-controller.ts';import {readDailyPlanView,changeDailyPlan,type DailyPlanClient} from '../src/daily-plans-api.ts';import {ApiError} from '../src/api-error.ts';
const owner=randomUUID(),companionId=randomUUID(),at='2026-10-09T12:00:00.000Z',date='2026-10-09';
const initial={ownerId:owner,companionId,localDate:date,timeZone:'America/New_York',dailyMinutes:90,paused:false,automaticStatus:'not_available',plan:null};
const intent={action:'add' as const,title:'Fictional user task',minutes:15};
const cmd=()=>({operationId:randomUUID(),companionId,localDate:date,planId:null,expectedRevision:0,...intent});
function saved(c:any,replayed=false){const plan={id:randomUUID(),ownerId:owner,companionId,localDate:date,timeZone:'America/New_York',generatedBy:'rules',briefMessageId:null,acceptedAt:null,revision:1,createdAt:at,updatedAt:at,lastOperationId:c.operationId,items:[{id:randomUUID(),candidateId:randomUUID(),title:c.title,minutes:c.minutes,rule:'user',state:'proposed',completedAt:null,completionSource:null,movedTo:null}]};return{view:{...initial,plan},operation:{id:c.operationId,action:c.action,localDate:c.localDate,planId:plan.id,appliedRevision:1,replayed}};}
function harness(run:(p:string,i:RequestInit)=>unknown){let active=true;const callbacks=new Set<()=>void>();const client:DailyPlanClient={account:{accountId:owner,generation:1},isCurrent:()=>active,subscribe(fn){callbacks.add(fn);return()=>callbacks.delete(fn);},request:async(p,i={})=>await run(p,i) as any};return{client,controller:new DailyPlanController(client,()=>{},40),invalidate(){active=false;for(const f of [...callbacks])f();}};}
async function until(f:()=>boolean){for(let i=0;i<150;i++){if(f())return;await new Promise(r=>setTimeout(r,2));}assert(f());}
async function ready(h:ReturnType<typeof harness>){h.controller.start();await until(()=>h.controller.snapshot().loaded&&!h.controller.snapshot().busy);}
test('lost acknowledgement keeps one owner command across refresh, failed observation and explicit retry',async()=>{let receipt:any,effects=0;const writes:any[]=[];const h=harness((path,init)=>{if(path.includes('/operations/'))throw new ApiError('Missing',404,'NOT_FOUND');if(!init.method)return receipt?.view??initial;const c=JSON.parse(String(init.body));writes.push(c);if(receipt)return{...receipt,operation:{...receipt.operation,replayed:true}};effects++;receipt=saved(c);throw Error('Lost');});await ready(h);h.controller.begin(intent);await until(()=>h.controller.snapshot().uncertain);await h.controller.refresh();await h.controller.observe();assert(h.controller.snapshot().pending);h.controller.begin(intent);assert.equal(writes.length,1);await h.controller.retry();assert.equal(effects,1);assert.deepEqual(writes[0],writes[1]);assert.equal(h.controller.snapshot().view?.plan?.items.length,1);assert.equal(h.controller.snapshot().pending,null);h.controller.stop();});
test('midnight recovery acknowledges yesterday while displaying a fresh empty today',async()=>{let c:any;const h=harness((path,i)=>{if(path.includes('/operations/'))return{...saved(c,true),view:{...initial,localDate:'2026-10-10'}};if(i.method){c=JSON.parse(String(i.body));throw Error('Lost');}return initial;});await ready(h);h.controller.begin(intent);await until(()=>h.controller.snapshot().uncertain);await h.controller.observe();assert.equal(h.controller.snapshot().view?.localDate,'2026-10-10');assert.equal(h.controller.snapshot().pending,null);assert.match(h.controller.snapshot().notice,/新一天/);h.controller.stop();});
test('account expiry, timeout and offline clear visible private tasks; late replies and reconnect cannot write',async()=>{let resolve!:(v:unknown)=>void,c:any,writes=0;const h=harness((_p,i)=>{if(i.method){writes++;c=JSON.parse(String(i.body));return new Promise(r=>resolve=r);}return initial;});await ready(h);h.controller.begin(intent);await until(()=>h.controller.snapshot().uncertain);const pending=h.controller.snapshot().pending;h.controller.suspend();assert.equal(h.controller.snapshot().view,null);h.controller.resume();await until(()=>h.controller.snapshot().loaded);assert.equal(h.controller.snapshot().pending,pending);assert.equal(writes,1);h.invalidate();resolve(saved(c));await new Promise(r=>setTimeout(r,5));assert.equal(h.controller.snapshot().view,null);assert.equal(h.controller.snapshot().pending,null);});
test('rest blocks new UI actions and confirmed revision/budget failures demand a fresh decision',async()=>{let writes=0;const paused=harness((_p,i)=>{if(i.method)writes++;return{...initial,paused:true};});await ready(paused);paused.controller.begin(intent);assert.equal(writes,0);paused.controller.stop();const h=harness((_p,i)=>{if(i.method){writes++;throw new ApiError('Budget',409,'DAILY_PLAN_BUDGET');}return initial;});await ready(h);h.controller.begin(intent);await until(()=>!h.controller.snapshot().busy);assert.equal(h.controller.snapshot().view,null);assert.equal(h.controller.snapshot().pending,null);assert.match(h.controller.snapshot().error,/预算/);h.controller.begin(intent);assert.equal(writes,1);h.controller.stop();});
test('transport binds owner, day, plan, revision and operation; paused payloads cannot contain task text',async()=>{const c=cmd(),r=saved(c);for(const value of [{...r,view:{...r.view,ownerId:randomUUID()}},{...r,view:{...r.view,paused:true}},{...r,operation:{...r.operation,id:randomUUID()}},{...r,operation:{...r.operation,localDate:'2026-10-08'}},{...r,operation:{...r.operation,planId:randomUUID()}},{...r,view:{...r.view,plan:{...r.view.plan,revision:2}}}])await assert.rejects(changeDailyPlan(harness(()=>value).client,c));await assert.rejects(changeDailyPlan(harness(()=>r).client,c,true));const h=harness(()=>initial);h.invalidate();await assert.rejects(readDailyPlanView(h.client));});
test('item commands use the item-specific PATCH route and cannot accept executable content',async()=>{const c=cmd(),r=saved(c);const itemId=r.view.plan.items[0].id;const done={operationId:randomUUID(),companionId,localDate:date,planId:r.view.plan.id,expectedRevision:1,action:'done',itemId};let path='',method='';const h=harness((p,i)=>{path=p;method=i.method!;throw new ApiError('Changed',409,'DAILY_PLAN_CHANGED');});await assert.rejects(changeDailyPlan(h.client,done));assert.equal(path,'/today/plan/items/'+itemId);assert.equal(method,'PATCH');await assert.rejects(changeDailyPlan(h.client,{...c,completionSource:'verified'}));});

test('a confirmed rest interrupts a pending task response and refreshes hidden state without losing the uncertain operation',async()=>{
 let resolve!:(v:unknown)=>void,c:any,rest=false;const h=harness((_p,i)=>{if(i.method){c=JSON.parse(String(i.body));return new Promise(r=>resolve=r);}return{...initial,paused:rest};});await ready(h);h.controller.begin(intent);rest=true;h.controller.suspend();h.controller.resume();await until(()=>h.controller.snapshot().loaded);assert.equal(h.controller.snapshot().view?.paused,true);assert(h.controller.snapshot().pending);resolve(saved(c));await new Promise(r=>setTimeout(r,5));assert.equal(h.controller.snapshot().view?.plan,null);assert.equal(h.controller.snapshot().view?.paused,true);h.controller.stop();
});

test('page lifecycle hides tasks, keeps an unknown write and reads the new day without replaying it',async()=>{
 const {bindPrivatePageLifecycle}=await import('../src/private-page-lifecycle.ts');
 const events=new EventTarget(),page=Object.assign(new EventTarget(),{visibilityState:'visible'});let online=true,reads=0,writes=0,resolve!:(v:unknown)=>void,c:any,newDay=false;
 const h=harness((_p,i)=>{if(i.method){writes++;c=JSON.parse(String(i.body));return new Promise(r=>resolve=r);}reads++;return newDay?{...initial,localDate:'2026-10-10'}:initial;});
 const lifecycle=bindPrivatePageLifecycle(h.controller,events,page,()=>online);
 await until(()=>h.controller.snapshot().loaded);h.controller.begin(intent);const pending=h.controller.snapshot().pending;assert(pending);
 page.visibilityState='hidden';page.dispatchEvent(new Event('visibilitychange'));assert.equal(h.controller.snapshot().view,null);assert.equal(h.controller.snapshot().pending,pending);
 newDay=true;lifecycle.refresh();events.dispatchEvent(new Event('online'));assert.equal(reads,1);
 online=false;events.dispatchEvent(new Event('offline'));page.visibilityState='visible';page.dispatchEvent(new Event('visibilitychange'));assert.equal(reads,1);
 online=true;events.dispatchEvent(new Event('online'));await until(()=>h.controller.snapshot().loaded);
 assert.equal(h.controller.snapshot().view?.localDate,'2026-10-10');assert.equal(writes,1);assert.equal(h.controller.snapshot().pending,pending);
 resolve(saved(c));await new Promise(r=>setTimeout(r,5));assert.equal(h.controller.snapshot().view?.localDate,'2026-10-10');assert.equal(h.controller.snapshot().pending,pending);
 h.invalidate();page.visibilityState='hidden';page.dispatchEvent(new Event('visibilitychange'));page.visibilityState='visible';page.dispatchEvent(new Event('visibilitychange'));assert.equal(reads,2);assert.equal(h.controller.snapshot().view,null);lifecycle.dispose();
});
