import { useCallback,useEffect,useRef,useState } from 'react';
import { CAREER_EXPERIENCE_KINDS,CAREER_STORY_TAGS,parseCareerLibraryCommand,careerLibrarySummary,type CareerLibraryKind,type CareerLibraryAction,type CareerLibraryRecord,type CareerProject,type CareerProjectSummary,type CareerStory,type CareerStorySummary,type CareerExperienceKind,type CareerDataSensitivity,type CareerStar,type CareerStoryTag } from '@companion/platform-contracts';
import { ApiError } from './api';
import { useRequiredPlatformAccountClient } from './account-client';
import { readCareerLibrary,readCareerLibraryRecord,readCareerProjectChoices,changeCareerLibrary,type LibraryView,type LibrarySummary } from './career-story-api';
import './career-target-view.css';
import './career-story-view.css';
const experienceLabels:Record<CareerExperienceKind,string>={course_project:'课程项目',independent_project:'独立项目',internship:'实习',employment:'工作经历',volunteering:'志愿经历',other:'其他经历'};
const privacyLabels:Record<CareerDataSensitivity,string>={normal:'普通：可在后续准备中使用',sensitive:'敏感：正文限主理人',restricted:'受限：只在你主动提起时使用'};
const sections=['situation','task','action','result'] as const,sectionLabels={situation:'S · 背景与约束',task:'T · 你的任务',action:'A · 你亲手做的事与取舍',result:'R · 结果、反馈或还不确定的地方'};
const tagLabels:Record<CareerStoryTag,string>={ownership:'主动承担',ambiguity:'面对不确定',conflict:'处理分歧',collaboration:'团队协作',problem_solving:'解决问题',leadership:'带领团队',learning:'学习新事物',other:'其他题型'};
const emptyStar=():CareerStar=>({situation:'',task:'',action:'',result:''});
interface Editor {record:Readonly<CareerLibraryRecord>|null;title:string;experienceKind:CareerExperienceKind|'';sensitivity:CareerDataSensitivity|'';occurredAt:string;context:string;contribution:string;outcome:string;english:CareerStar;chinese:CareerStar;tags:CareerStoryTag[];projects:{id:string;revision:number}[];}
function editorFor(r:Readonly<CareerLibraryRecord>|null):Editor {const p=r&&'kind' in r?r:null,s=r&&!('kind' in r)?r:null;return {record:r,title:r?.title??'',experienceKind:r?.experienceKind??'',sensitivity:r?.sensitivity??'',occurredAt:p?.occurredAt??'',context:p?.context??'',contribution:p?.contribution??'',outcome:p?.outcome??'',english:{...(s?.english??emptyStar())},chinese:{...(s?.chinese??emptyStar())},tags:[...(s?.tags??[])],projects:[...(s?.projects??[])]};}
export function CareerStoryPage({onLogout,initialStoryId}:{onLogout:()=>void;initialStoryId?:string}){
 const client=useRequiredPlatformAccountClient(),live=useRef(true),epoch=useRef(0),request=useRef<AbortController|null>(null),pending=useRef<{kind:CareerLibraryKind;action:CareerLibraryAction;id:string|null;body:Record<string,unknown>}|null>(null);
 const [kind,setKind]=useState<CareerLibraryKind>('story'),[records,setRecords]=useState<readonly Readonly<LibraryView<LibrarySummary>>[]>([]),[next,setNext]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false),[editor,setEditor]=useState<Editor|null>(null),[detail,setDetail]=useState<Readonly<LibraryView<CareerLibraryRecord>>|null>(null),[choices,setChoices]=useState<readonly Readonly<CareerProjectSummary>[]>([]),[confirmation,setConfirmation]=useState<{record:Readonly<LibrarySummary>;action:'confirm'|'withdraw'|'delete'}|null>(null),[language,setLanguage]=useState<'english'|'chinese'>('english');
 const current=()=>live.current&&client.isCurrent();
 const load=useCallback(async(after:string|null=null)=>{if(!live.current||!client.isCurrent()||request.current)return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);
  try{const page=await readCareerLibrary(client,kind,after,c.signal);if(live.current&&client.isCurrent()&&epoch.current===n){setRecords(old=>after?[...old,...page.records.filter(v=>!old.some(p=>p.record.id===v.record.id))]:page.records);setNext(page.nextAfter);setLoaded(true);setError('');}}
  catch(e){if(live.current&&client.isCurrent()&&!c.signal.aborted)setError(e instanceof ApiError?e.message:'经历暂时没读到，请重新读取。');}finally{if(live.current&&client.isCurrent()&&epoch.current===n){request.current=null;setBusy(false);}}
 },[client,kind]);
 useEffect(()=>{let active=true;live.current=true;setRecords([]);setDetail(null);setEditor(null);setConfirmation(null);setChoices([]);setLoaded(false);setNext(null);void load().then(()=>{if(active&&initialStoryId&&kind==='story')void open(initialStoryId);});const unsubscribe=client.subscribe(()=>{if(!client.isCurrent()){live.current=false;epoch.current++;request.current?.abort();pending.current=null;setRecords([]);setDetail(null);setEditor(null);setConfirmation(null);setChoices([]);setNext(null);setLoaded(false);setUncertain(false);}});
  return()=>{active=false;live.current=false;epoch.current++;request.current?.abort();request.current=null;pending.current=null;unsubscribe();};
 },[client,load,initialStoryId]);
 async function open(id:string|null,edit=false){if(busy||uncertain||request.current||!current())return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);
  try{const [view,projects]=await Promise.all([id?readCareerLibraryRecord(client,kind,id,c.signal):Promise.resolve(null),edit&&kind==='story'?readCareerProjectChoices(client,c.signal):Promise.resolve([])]);if(current()&&epoch.current===n){if(edit){setChoices(projects);setEditor(editorFor(view?.record??null));setDetail(null);}else {setDetail(view);if(view)setRecords(old=>old.some(v=>v.record.id===view.record.id)?old:[{record:careerLibrarySummary(kind,view.record),evidenceAvailability:view.evidenceAvailability},...old]);}setError('');}}
  catch(e){if(current()&&!c.signal.aborted)setError(e instanceof ApiError?e.message:'这段经历暂时没读到。');}finally{c.abort();if(current()&&epoch.current===n){request.current=null;setBusy(false);}}
 }
 async function execute(){const op=pending.current;if(!op||busy||request.current||!current())return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);setError('');
  try{const result=await changeCareerLibrary(client,op.kind,op.action,op.id,op.body,c.signal);if(!current()||epoch.current!==n)return;setRecords(old=>[...(result.record?[{record:careerLibrarySummary(op.kind,result.record),evidenceAvailability:result.evidenceAvailability}]:[]),...old.filter(v=>v.record.id!==result.operation.recordId)]);setDetail(result.record?{record:result.record,evidenceAvailability:result.evidenceAvailability}:null);pending.current=null;setUncertain(false);setEditor(null);setConfirmation(null);}
  catch(e){if(!current()||c.signal.aborted)return;if(e instanceof ApiError&&e.status>=400&&e.status<500){pending.current=null;setUncertain(false);setError(e.status===409?'经历或关联事实已经变化，请重新读取，再核对版本。':e.message);}else{setUncertain(true);setError('暂时不能确认这次操作是否完成。可以重新读取，或用原操作重试。');}}
  finally{if(current()&&epoch.current===n){request.current=null;setBusy(false);}}
 }
 function start(action:CareerLibraryAction,id:string|null,body:Record<string,unknown>){if(busy||uncertain||request.current||!current())return;const command=parseCareerLibraryCommand(kind,action,{...body,operationId:crypto.randomUUID()});pending.current={kind,action,id,body:{...command}};void execute();}
 function save(){if(!editor||!editor.experienceKind||!editor.sensitivity)return;const r=editor.record;if(r&&records.find(v=>v.record.id===r.id)?.record.revision!==r.revision){setError('你正在编辑旧版本，先核对最新记录再保存。');return;}
  const body={expectedRevision:r?.revision??0,title:editor.title,experienceKind:editor.experienceKind,sensitivity:editor.sensitivity,...(kind==='project'?{occurredAt:editor.occurredAt,context:editor.context,contribution:editor.contribution,outcome:editor.outcome}:{english:editor.english,chinese:editor.chinese,tags:editor.tags,projects:editor.projects})};
  try{start(r?'edit':'create',r?.id??null,body);}catch{setError('请填写标题、经历类型和敏感度；项目事实需要明确的发生时间与背景，每段最多 4000 字。');}
 }
 function confirm(){if(!confirmation)return;const r=confirmation.record;if(records.find(v=>v.record.id===r.id)?.record.revision!==r.revision){setError('记录已经变化，请重新读取再确认。');return;}start(confirmation.action,r.id,{expectedRevision:r.revision});}
 const itemStatus=(r:LibrarySummary)=>'kind' in r?r.state==='withdrawn'?'已撤回':r.verification==='user_confirmed'?'本人已确认事实':'本人填写，待确认':r.status==='confirmed'?'已确认故事':'草稿';
 const availabilityText={current:'关联事实为当前确认版本',unconfirmed:'关联事实还需要本人确认',stale:'关联事实已变更，需要重新核对',withdrawn:'关联事实已撤回，暂不能引用',missing:'关联事实已移除，暂不能引用'};
 return <main className="career-target-page career-story-page"><nav><a href="/">回到对话</a><a href="/journey/targets">目标方向</a><a href="/journey/jobs">收藏的岗位</a><button type="button" onClick={onLogout}>退出登录</button></nav><section className="career-target-panel"><header><h1>把你的经历讲清楚</h1><p>课程项目也有值得展开的判断和取舍。先记下事实，再整理成你能讲出口的故事。</p></header>
  <div className="career-target-actions" role="group" aria-label="故事库与项目事实"><button type="button" aria-pressed={kind==='story'} disabled={busy||uncertain} onClick={()=>setKind('story')}>故事库</button><button type="button" aria-pressed={kind==='project'} disabled={busy||uncertain} onClick={()=>setKind('project')}>项目事实</button><button type="button" disabled={busy||uncertain} onClick={()=>void open(null,true)}>{kind==='story'?'新建故事':'记录项目事实'}</button><button type="button" disabled={busy} onClick={()=>void load()}>重新读取</button></div>
  {busy&&<p role="status">正在读取或保存…</p>}{error&&<p role="alert" className="career-target-notice">{error}</p>}{uncertain&&<button type="button" disabled={busy} onClick={()=>void execute()}>用原操作重试</button>}
  {loaded&&!records.length&&!editor&&<p>{kind==='story'?'还没有故事。和前辈聊一段经历，或者在面试间练完后存一个。':'还没记录项目事实。先区分团队做了什么、你亲手做了什么，以及哪些结果还不确定。'}</p>}
  {editor&&<form className="career-target-editor" onSubmit={e=>{e.preventDefault();save();}}><h2>{editor.record?'修改这段经历':kind==='story'?'新建故事草稿':'记录一段项目事实'}</h2><p>先写你亲手做的事。数字、反馈和结果记下你能核对的部分，想不起的可以留待补充。课程项目也能成为一个清楚的案例。</p>
   <label>标题<input value={editor.title} required disabled={busy||uncertain} onChange={e=>setEditor({...editor,title:e.target.value})}/></label>
   <label>经历类型<select value={editor.experienceKind} required disabled={busy||uncertain} onChange={e=>setEditor({...editor,experienceKind:e.target.value as Editor['experienceKind']})}><option value="">请选择</option>{CAREER_EXPERIENCE_KINDS.map(k=><option key={k} value={k}>{experienceLabels[k]}</option>)}</select></label>
   <label>敏感度<select value={editor.sensitivity} required disabled={busy||uncertain} onChange={e=>setEditor({...editor,sensitivity:e.target.value as Editor['sensitivity']})}><option value="">由你选择</option>{(Object.keys(privacyLabels) as CareerDataSensitivity[]).map(k=><option key={k} value={k}>{privacyLabels[k]}</option>)}</select></label><p>现在仅保存到你的私人资料；后续对话使用还需来源检查与权限确认。</p>
   {kind==='project'?<><label>发生时间（UTC，填写你能确认的时间）<input type="datetime-local" required value={editor.occurredAt.slice(0,16)} disabled={busy||uncertain} onChange={e=>setEditor({...editor,occurredAt:e.target.value?e.target.value+':00.000Z':''})}/></label>{(['context','contribution','outcome'] as const).map((key,i)=><label key={key}>{['项目背景与团队任务','你亲手做的事','结果、反馈或不确定的地方'][i]}<textarea value={editor[key]} disabled={busy||uncertain} onChange={e=>setEditor({...editor,[key]:e.target.value})}/></label>)}</>:<>
    <div className="career-story-language"><button type="button" aria-pressed={language==='english'} onClick={()=>setLanguage('english')}>英文正文</button><button type="button" aria-pressed={language==='chinese'} onClick={()=>setLanguage('chinese')}>中文要点</button></div><div className={'career-story-star-grid show-'+language}>{(['english','chinese'] as const).map(lang=><section key={lang} className={'star-'+lang}><h3>{lang==='english'?'英文正文':'中文要点'}</h3>{sections.map(key=><label key={key}>{sectionLabels[key]}<textarea value={editor[lang][key]} disabled={busy||uncertain} onChange={e=>setEditor({...editor,[lang]:{...editor[lang],[key]:e.target.value}})}/></label>)}</section>)}</div>
    <fieldset disabled={busy||uncertain}><legend>题型标签</legend>{CAREER_STORY_TAGS.map(tag=><label className="career-story-checkbox" key={tag}><input type="checkbox" checked={editor.tags.includes(tag)} onChange={e=>setEditor({...editor,tags:e.target.checked?[...editor.tags,tag]:editor.tags.filter(t=>t!==tag)})}/>{tagLabels[tag]}</label>)}</fieldset>
    <fieldset disabled={busy||uncertain}><legend>关联你保存的项目事实（可不选）</legend><p>项目事实的版本和隐私会一起核对。本人确认不等于导师审核。</p>{choices.filter(p=>p.state==='active').map(p=><label className="career-story-checkbox" key={p.id}><input type="checkbox" checked={editor.projects.some(v=>v.id===p.id&&v.revision===p.revision)} onChange={e=>setEditor({...editor,projects:e.target.checked?[...editor.projects.filter(v=>v.id!==p.id),{id:p.id,revision:p.revision}]:editor.projects.filter(v=>v.id!==p.id)})}/>{p.title} · {experienceLabels[p.experienceKind]} · {p.verification==='user_confirmed'?'本人已确认':'待本人确认'} · {p.sensitivity==='normal'?'普通':p.sensitivity==='sensitive'?'敏感':'受限'}</label>)}{editor.projects.filter(ref=>!choices.some(p=>p.id===ref.id&&p.revision===ref.revision&&p.state==='active')).map(ref=><label className="career-story-checkbox" key={ref.id}><input type="checkbox" checked onChange={()=>setEditor({...editor,projects:editor.projects.filter(v=>v.id!==ref.id)})}/>旧关联已变更、撤回或移除；取消后重新选择当前事实</label>)}{!choices.length&&<p>还没保存项目事实。可以先保存故事草稿，再去记录经历。</p>}</fieldset></>}
   <div className="career-target-actions"><button type="submit" disabled={busy||uncertain}>保存{kind==='story'?'草稿':'事实'}</button><button type="button" disabled={busy||uncertain} onClick={()=>setEditor(null)}>先不改了</button></div></form>}
  {confirmation&&<section className="career-target-confirmation"><p>{confirmation.action==='delete'?'移除保存的内容？其他故事中的关联会失效，需要重新核对。':confirmation.action==='withdraw'?'撤回这段项目事实？关联故事暂不能引用它。':'确认这段经历中的本人行动、数字与结果？确认的是你记录的事实，不代表导师审核。修改后需要重新确认。'}</p><div className="career-target-actions"><button type="button" disabled={busy||uncertain} onClick={confirm}>确认这个选择</button><button type="button" disabled={busy||uncertain} onClick={()=>setConfirmation(null)}>再核对一下</button></div></section>}
  {detail&&<section className="career-target-editor"><h2>{detail.record.title}</h2><p>{experienceLabels[detail.record.experienceKind]} · {itemStatus(detail.record)}</p><button type="button" onClick={()=>setDetail(null)}>收起正文</button>{'kind' in detail.record?<>{(['context','contribution','outcome'] as const).map((key,i)=><section key={key}><h3>{['项目背景','本人行动','结果与反馈'][i]}</h3><p className="career-story-copy">{(detail.record as CareerProject)[key]||'暂未填写'}</p></section>)}</>:<><div className="career-story-star-grid">{(['english','chinese'] as const).map(lang=><section key={lang}><h3>{lang==='english'?'英文正文':'中文要点'}</h3>{sections.map(key=><section key={key}><h4>{sectionLabels[key]}</h4><p className="career-story-copy">{(detail.record as CareerStory)[lang][key]||'暂未填写'}</p></section>)}</section>)}</div><p>{availabilityText[detail.evidenceAvailability!]}</p></>}</section>}
  <ul className="career-target-list">{records.map(v=><li key={v.record.id}><h2>{kind==='story'?<a href={'/journey/stories/'+v.record.id}>{v.record.title}</a>:v.record.title}</h2><p>{experienceLabels[v.record.experienceKind]} · {itemStatus(v.record)} · {v.record.sensitivity==='normal'?'普通':v.record.sensitivity==='sensitive'?'敏感':'受限'}</p>{v.evidenceAvailability&&<p>{availabilityText[v.evidenceAvailability]}</p>}<div className="career-target-actions"><button type="button" disabled={busy||uncertain} onClick={()=>void open(v.record.id)}>查看正文</button><button type="button" disabled={busy||uncertain} onClick={()=>void open(v.record.id,true)}>修改</button>{('kind' in v.record?v.record.verification!=='user_confirmed'||v.record.state==='withdrawn':v.record.status!=='confirmed')&&<button type="button" disabled={busy||uncertain} onClick={()=>setConfirmation({record:v.record,action:'confirm'})}>{'kind' in v.record&&v.record.state==='withdrawn'?'恢复并确认':'核对后确认'}</button>}{'kind' in v.record&&v.record.state==='active'&&<button type="button" disabled={busy||uncertain} onClick={()=>setConfirmation({record:v.record,action:'withdraw'})}>撤回事实</button>}<button type="button" disabled={busy||uncertain} onClick={()=>setConfirmation({record:v.record,action:'delete'})}>移除</button></div></li>)}</ul>{next&&<button type="button" disabled={busy||uncertain} onClick={()=>void load(next)}>继续看保存的经历</button>}
 </section></main>;
}
