import { useCallback,useEffect,useRef,useState } from 'react';
import { CAREER_ROLE_FAMILIES,parseManualJobCommand,manualJobSummary,manualJobsDuplicate,type ManualJob,type ManualJobSummary,type CareerTargetRoleFamily,type ManualJobAction } from '@companion/platform-contracts';
import { ApiError } from './api';
import { useRequiredPlatformAccountClient } from './account-client';
import { readManualJobs,readManualJob,readManualJobDuplicates,changeManualJob } from './manual-job-api';
import './career-target-view.css';
import './manual-job-view.css';
const labels:Record<CareerTargetRoleFamily,string>={swe:'Software Engineering',mle:'Machine Learning Engineering',ds:'Data Science',da:'Data Analytics',de:'Data Engineering',hw:'硬件 / 本专业',other:'其他方向'};
const blank={employer:'',title:'',canonicalUrl:'',roleFamily:'' as CareerTargetRoleFamily|'',location:'',deadline:'',privateNote:'',jobText:''};
export function ManualJobPage({onLogout}:{onLogout:()=>void}){
 const client=useRequiredPlatformAccountClient(),live=useRef(true),epoch=useRef(0),request=useRef<AbortController|null>(null),pending=useRef<{action:ManualJobAction;id:string|null;body:Record<string,unknown>}|null>(null);
 const [jobs,setJobs]=useState<readonly Readonly<ManualJobSummary>[]>([]),[next,setNext]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[form,setForm]=useState<typeof blank|null>(null),[detail,setDetail]=useState<Readonly<ManualJob>|null>(null),[remove,setRemove]=useState<Readonly<ManualJobSummary>|null>(null),[duplicate,setDuplicate]=useState(false),[matches,setMatches]=useState<readonly Readonly<ManualJobSummary>[]>([]);
 const current=()=>live.current&&client.isCurrent();
 const load=useCallback(async(after:string|null=null)=>{if(!live.current||!client.isCurrent()||request.current)return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);
  try{const page=await readManualJobs(client,after,c.signal);if(live.current&&client.isCurrent()&&epoch.current===n){setJobs(previous=>after?[...previous,...page.jobs.filter(j=>!previous.some(p=>p.id===j.id))]:page.jobs);setNext(page.nextAfter);setLoaded(true);setError('');}}
  catch(e){if(live.current&&client.isCurrent()&&!c.signal.aborted)setError(e instanceof ApiError?e.message:'岗位暂时没读到，请重新读取。');}
  finally{if(live.current&&client.isCurrent()&&epoch.current===n){request.current=null;setBusy(false);}}
 },[client]);
 useEffect(()=>{live.current=true;void load();const unsubscribe=client.subscribe(()=>{if(!client.isCurrent()){live.current=false;epoch.current++;request.current?.abort();pending.current=null;setJobs([]);setNext(null);setForm(null);setDetail(null);setRemove(null);setDuplicate(false);setMatches([]);setUncertain(false);setLoaded(false);}});
  return()=>{live.current=false;epoch.current++;request.current?.abort();request.current=null;pending.current=null;unsubscribe();};
 },[client,load]);
 async function open(id:string){if(busy||request.current||!current())return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);try{const job=await readManualJob(client,id,c.signal);if(current()&&epoch.current===n){setDetail(job);setError('');}}catch(e){if(current()&&!c.signal.aborted)setError(e instanceof ApiError?e.message:'这条岗位暂时没读到。');}finally{if(current()&&epoch.current===n){request.current=null;setBusy(false);}}}
 async function execute(){const operation=pending.current;if(!operation||busy||request.current||!current())return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);setError('');
  try{const result=await changeManualJob(client,operation.action,operation.id,operation.body,c.signal);if(!current()||epoch.current!==n)return;setJobs(old=>[...(result.job?[manualJobSummary(result.job)]:[]),...old.filter(j=>j.id!==result.operation.observationId)]);pending.current=null;setUncertain(false);setForm(null);setRemove(null);setDuplicate(false);setDetail(result.job);}
  catch(e){if(!current()||c.signal.aborted)return;if(e instanceof ApiError&&e.status>=400&&e.status<500){pending.current=null;setUncertain(false);if(e.code==='MANUAL_JOB_DUPLICATE'){try{const actual=await readManualJobDuplicates(client,operation.body,c.signal);if(current()&&epoch.current===n){setMatches(actual);setDuplicate(true);setError('这个岗位之前收藏过。可以打开原来的那条，也可以确认新建一份。');}}catch{if(current()&&!c.signal.aborted)setError('发现重复收藏，但旧记录暂时没读到；请重新读取后再保存。');}}else setError(e.status===409?'保存状态有变化，请重新读取再核对。':e.message);}else{setUncertain(true);setError('还不能确认这次保存是否完成。可以重新读取，或用原操作重试。');}}
  finally{if(current()&&epoch.current===n){request.current=null;setBusy(false);}}
 }
 function start(action:ManualJobAction,id:string|null,body:Record<string,unknown>){if(busy||uncertain||request.current||!current())return;const parsed=parseManualJobCommand(action,{...body,operationId:crypto.randomUUID()});pending.current={action,id,body:{...parsed}};void execute();}
 function save(allowDuplicate=false){if(!form||!form.roleFamily)return;try{const body={...form,expectedRevision:0,deadlineAt:form.deadline?form.deadline+':00.000Z':null,deadlineTimeZone:form.deadline?'UTC':null,allowDuplicate};delete (body as any).deadline;
  const parsed=parseManualJobCommand('create',{...body,operationId:crypto.randomUUID()});const found=jobs.filter(j=>manualJobsDuplicate(j,parsed as Pick<ManualJob,'canonicalUrl'|'employer'|'title'>));if(!allowDuplicate&&found.length){setMatches(found);setDuplicate(true);return;}start('create',null,body);
 }catch{setError('请填写公司、岗位、岗位家族和 JD 原文；链接需为 HTTPS，截止时间请按 UTC 填写。');}}
 return <main className="career-target-page manual-job-page"><nav><a href="/">回到对话</a><a href="/journey/targets">目标方向</a><a href="/journey/applications">投递旅程</a><button type="button" onClick={onLogout}>退出登录</button></nav><section className="career-target-panel"><header><h1>你收藏的岗位</h1><p>把想投的 JD 留下来，再逐条核对资料和准备材料。</p></header>
  <div className="career-target-actions"><button type="button" disabled={busy||uncertain} onClick={()=>{setForm({...blank});setDuplicate(false);}}>收藏一个岗位</button><button type="button" disabled={busy} onClick={()=>void load()}>重新读取</button></div>
  {busy&&<p role="status">正在读取或保存…</p>}{error&&<p role="alert" className="career-target-notice">{error}</p>}{uncertain&&<button type="button" disabled={busy} onClick={()=>void execute()}>用原操作重试</button>}
  {loaded&&!jobs.length&&!form&&<p className="career-target-empty">还没有收藏的岗位。贴一段 JD 就能开始。</p>}
  {form&&<form className="career-target-editor" onSubmit={e=>{e.preventDefault();save();}}><h2>核对后收藏</h2><p>这些信息由你填写；链接只保存，不会自动打开或抓取。</p>{(['employer','title','canonicalUrl','location'] as const).map((key,i)=><label key={key}>{['公司','岗位名称','岗位链接（可留空）','地点（可留空）'][i]}<input value={form[key]} required={i<2} disabled={busy||uncertain||duplicate} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
   <label>岗位家族<select required value={form.roleFamily} disabled={busy||uncertain||duplicate} onChange={e=>setForm({...form,roleFamily:e.target.value as typeof form.roleFamily})}><option value="">请选择</option>{CAREER_ROLE_FAMILIES.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>
   <label>截止时间（UTC，可留空）<input type="datetime-local" value={form.deadline} disabled={busy||uncertain||duplicate} onChange={e=>setForm({...form,deadline:e.target.value})}/></label>
   <label>JD 原文<textarea required value={form.jobText} disabled={busy||uncertain||duplicate} onChange={e=>setForm({...form,jobText:e.target.value})}/></label><label>私人备注（可留空）<textarea value={form.privateNote} disabled={busy||uncertain||duplicate} onChange={e=>setForm({...form,privateNote:e.target.value})}/></label>
   {duplicate&&<section aria-label="重复收藏确认"><p>这个岗位之前收藏过。要打开原来的那条，还是新建一份？</p>{matches.map(j=><button type="button" disabled={busy||uncertain} key={j.id} onClick={()=>void open(j.id)}>打开 {j.title} · {new Date(j.observedAt).toLocaleDateString()}</button>)}<button type="button" disabled={busy||uncertain} onClick={()=>save(true)}>还是新建</button><button type="button" disabled={busy||uncertain} onClick={()=>setDuplicate(false)}>回去修改</button></section>}
   <div className="career-target-actions"><button type="submit" disabled={busy||uncertain||duplicate}>确认收藏</button><button type="button" disabled={busy||uncertain} onClick={()=>{setForm(null);setDuplicate(false);}}>先不保存</button></div></form>}
  {remove&&<section className="career-target-confirmation"><p>移除「{remove.title}」？保存的 JD 和私人备注会删除。</p><div className="career-target-actions"><button type="button" disabled={busy||uncertain} onClick={()=>start('delete',remove.id,{expectedRevision:remove.revision})}>确认移除</button><button type="button" disabled={busy||uncertain} onClick={()=>setRemove(null)}>保留</button></div></section>}
  {detail&&<section className="career-target-editor" aria-label="岗位原文"><div className="career-target-actions"><h2>{detail.employer} · {detail.title}</h2><button type="button" onClick={()=>setDetail(null)}>收起原文</button></div><p>你贴的 JD · 没核实是否还开放</p><p>原句检查于 {new Date(detail.checkedAt).toLocaleString()}（检查的是你粘贴的文字）</p><h3>身份与工作授权相关原句</h3>{detail.sponsorshipEvidence.length?<div>{detail.sponsorshipEvidence.map(e=><blockquote key={e.start}>{e.text}</blockquote>)}{detail.evidenceOverflow&&<p>相关原句较多，这里显示前 50 条，请同时核对完整原文。</p>}</div>:<p>没找到相关原句（{new Date(detail.checkedAt).toLocaleDateString()} 查看），提交前请自己扫一眼。</p>}<details><summary>完整 JD 原文</summary><pre>{detail.jobText}</pre></details>{detail.privateNote&&<details><summary>私人备注</summary><pre>{detail.privateNote}</pre></details>}<p>需要更正时，可以移除后重新收藏一份。</p></section>}
  <ul className="career-target-list">{jobs.map(j=><li key={j.id}><h2>{j.title}</h2><p>{j.employer} · {labels[j.roleFamily]}{j.location?' · '+j.location:''}</p><p>你贴的 JD · 没核实是否还开放</p><p>收藏于 {new Date(j.observedAt).toLocaleString()}</p>{j.deadlineAt&&<p>你填写的截止时间：{new Date(j.deadlineAt).toISOString().replace('T',' ').replace('.000Z',' UTC')}</p>}<div className="career-target-actions"><button type="button" disabled={busy} onClick={()=>void open(j.id)}>核对原句</button>{j.canonicalUrl&&<a href={j.canonicalUrl} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">打开保存的链接</a>}<button type="button" disabled={busy||uncertain} onClick={()=>setRemove(j)}>移除</button></div></li>)}</ul>{next&&<button type="button" disabled={busy} onClick={()=>void load(next)}>继续看已收藏的岗位</button>}
 </section></main>;
}
