import { useCallback,useEffect,useRef,useState } from 'react';
import { CAREER_ROLE_FAMILIES,parseResumeReviewCommand,type CareerRoleFamily,type ResumeReviewItem,type ResumeReviewView,type ResumeReviewAction } from '@companion/platform-contracts';
import { ApiError } from './api';
import { useRequiredPlatformAccountClient } from './account-client';
import { readResumeReviews,readResumeReview,changeResumeReview,observeResumeIntent,type PendingResumeIntent } from './resume-review-api';
import './resume-review-view.css';
const labels={swe:'软件工程',mle:'机器学习工程',ds:'数据科学',da:'数据分析',de:'数据工程',hw:'硬件等本专业方向',other:'其他方向'};
const states={pending:'等你确认',approved:'已确认 · 可以用了',declined:'不要了',expired:'过期了',superseded:'已被替换'} as const;
interface Editor {item:Readonly<ResumeReviewItem>|null;source:Readonly<ResumeReviewItem>|null;track:CareerRoleFamily|'';label:string;text:string;}
export function ResumeReviewPage({onLogout,initialItemId}:{onLogout:()=>void;initialItemId?:string}){
 const client=useRequiredPlatformAccountClient(),live=useRef(true),epoch=useRef(0),request=useRef<AbortController|null>(null),intent=useRef<PendingResumeIntent|null>(null);
 const [items,setItems]=useState<readonly Readonly<ResumeReviewItem>[]>([]),[next,setNext]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[waiting,setWaiting]=useState(false),[uncertain,setUncertain]=useState(false),[detail,setDetail]=useState<Readonly<ResumeReviewView>|null>(null),[editor,setEditor]=useState<Editor|null>(null),[confirm,setConfirm]=useState<{item:Readonly<ResumeReviewItem>;action:ResumeReviewAction}|null>(null),[copied,setCopied]=useState(false);
 const current=()=>live.current&&client.isCurrent();
 const load=useCallback(async(after:string|null=null)=>{if(!live.current||!client.isCurrent()||request.current)return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);try{const page=await readResumeReviews(client,after,c.signal);if(live.current&&client.isCurrent()&&epoch.current===n){setItems(old=>after?[...old,...page.items.filter(p=>!old.some(v=>v.id===p.id))]:page.items);setNext(page.nextAfter);setLoaded(true);setError('');}}catch(e){if(live.current&&client.isCurrent()&&!c.signal.aborted)setError(e instanceof ApiError?e.message:'版本暂时没读到，请重新读取。');}finally{if(live.current&&client.isCurrent()&&epoch.current===n){request.current=null;setBusy(false);}}},[client]);
 useEffect(()=>{let active=true;live.current=true;void load().then(()=>{if(active&&initialItemId)void open(initialItemId);});const unsubscribe=client.subscribe(()=>{if(!client.isCurrent()){live.current=false;epoch.current++;request.current?.abort();intent.current=null;setItems([]);setDetail(null);setEditor(null);setConfirm(null);setNext(null);setLoaded(false);setUncertain(false);setWaiting(false);}});return()=>{active=false;live.current=false;epoch.current++;request.current?.abort();request.current=null;intent.current=null;unsubscribe();};},[client,load,initialItemId]);
 async function open(id:string,edit=false,fork=false){if(!current()||request.current||busy||uncertain)return;const c=new AbortController(),n=++epoch.current;request.current=c;setBusy(true);setCopied(false);try{const v=await readResumeReview(client,id,c.signal);if(current()&&epoch.current===n){setDetail(v);setItems(old=>[v.item,...old.filter(p=>p.id!==id)]);if(edit||fork)setEditor({item:fork?null:v.item,source:fork?v.item:null,track:v.item.track,label:v.item.label,text:v.payload.text});setError('');}}catch(e){if(current()&&!c.signal.aborted)setError(e instanceof ApiError?e.message:'原稿暂时没读到。');}finally{if(current()&&epoch.current===n){request.current=null;setBusy(false);}}}
 function accept(saved:Awaited<ReturnType<typeof changeResumeReview>>){setItems(old=>[...(saved.view?[saved.view.item]:[]),...old.filter(v=>v.id!==saved.operation.itemId)]);setDetail(saved.view);setEditor(null);setConfirm(null);intent.current=null;setUncertain(false);setError('');setCopied(false);}
 async function execute(){const pending=intent.current;if(!pending||!current()||request.current)return;const n=++epoch.current,c=new AbortController();request.current=c;setBusy(true);setWaiting(false);setError('');let timedOut=false;
  const timer=window.setTimeout(()=>{if(current()&&epoch.current===n){timedOut=true;setWaiting(true);c.abort();}},8000);
  try{const saved=await changeResumeReview(client,pending,c.signal);if(current()&&epoch.current===n)accept(saved);}
  catch(e){if(!current()||epoch.current!==n)return;if(timedOut){
   const observer=new AbortController();request.current=observer;const observerTimer=window.setTimeout(()=>observer.abort(),5000);
   try{const saved=await observeResumeIntent(client,pending,observer.signal);if(current()&&epoch.current===n)accept(saved);}catch{if(current()&&epoch.current===n){setUncertain(true);setError('还不能确认这次操作是否完成。可以重新读取，或用原操作重试。');}}finally{window.clearTimeout(observerTimer);}
  }else if(!c.signal.aborted){if(e instanceof ApiError&&e.status>=400&&e.status<500){intent.current=null;setUncertain(false);setError(e.status===409?'内容或状态已变化，请重新读取后核对。':e.message);}else{setUncertain(true);setError('暂时不能确认这次操作是否完成。可以用原操作重试。');}}}
  finally{window.clearTimeout(timer);if(current()&&epoch.current===n){request.current=null;setBusy(false);setWaiting(false);}}
 }
 function start(action:ResumeReviewAction,id:string|null,body:Record<string,unknown>){if(!current()||request.current||uncertain)return;try{intent.current={action,itemId:id,body:parseResumeReviewCommand(action,{...body,operationId:crypto.randomUUID()})};void execute();}catch{setError('请选择方向、填写版本名称和完整原稿，正文最多 50000 字。');}}
 function save(){if(!editor||!editor.track)return;const original=editor.item;if(original&&items.find(v=>v.id===original.id)?.revision!==original.revision){setError('你在修改旧版本，请先重新读取。');return;}start(original?'edit':'create',original?.id??null,{expectedRevision:original?.revision??0,label:editor.label,text:editor.text,...(original?{payloadDigest:original.payloadDigest}:{track:editor.track,...(editor.source?{derivedFromId:editor.source.resumeVersionId}:{})})});}
 function decide(){if(!confirm)return;const item=confirm.item;if(items.find(v=>v.id===item.id)?.revision!==item.revision){setError('版本已变化，请重新核对。');return;}start(confirm.action,item.id,{expectedRevision:item.revision,payloadDigest:item.payloadDigest});}
 async function copy(){if(!detail||detail.item.status!=='approved'||!current())return;const n=epoch.current;try{await navigator.clipboard.writeText(detail.payload.text);if(current()&&epoch.current===n)setCopied(true);}catch{if(current())setError('没复制上，可以选中正文自己复制。');}}
 return <main className="resume-review-page"><nav><a href="/">回到对话</a><a href="/journey/stories">故事库</a><a href="/journey/jobs">收藏的岗位</a><span>Career Companion · AI</span><button type="button" onClick={onLogout}>退出登录</button></nav><section className="resume-review-panel"><header><h1>核对这一版，再用它</h1><p>先把你现有的简历存下来。确认的是你亲手核对过的完整内容；以后修改，会另外留下一版。</p></header><div className="resume-review-actions"><button type="button" disabled={busy||uncertain} onClick={()=>{setEditor({item:null,source:null,track:'',label:'原稿',text:''});setDetail(null);}}>粘贴简历原稿</button><button type="button" disabled={busy} onClick={()=>void load()}>重新读取</button></div>
 {busy&&<p role="status">{waiting?'还在确认，先别关页面。正在核对服务端状态…':'正在读取或保存…'}</p>}{error&&<p role="alert" className="resume-review-notice">{error}</p>}{uncertain&&<button type="button" disabled={busy} onClick={()=>void execute()}>用原操作重试</button>}{loaded&&!items.length&&!editor&&<p>还没有简历。先贴文字，核对后就可以作为第一版使用。</p>}
 {editor&&<form className="resume-review-editor" onSubmit={e=>{e.preventDefault();save();}}><h2>{editor.item?'修改待确认原稿':editor.source?'从已确认版本另存草稿':'粘贴你的简历'}</h2><p>这里只保存你填写的内容。经历、数字和个人贡献由你核对，不会自动改写。</p><label>岗位方向<select required disabled={busy||uncertain||Boolean(editor.item||editor.source)} value={editor.track} onChange={e=>setEditor({...editor,track:e.target.value as Editor['track']})}><option value="">请选择</option>{CAREER_ROLE_FAMILIES.map(t=><option key={t} value={t}>{labels[t]}</option>)}</select></label><label>版本名称<input required maxLength={120} disabled={busy||uncertain} value={editor.label} onChange={e=>setEditor({...editor,label:e.target.value})}/></label><label>简历全文<textarea required disabled={busy||uncertain} value={editor.text} onChange={e=>setEditor({...editor,text:e.target.value})}/></label><p>新草稿会替换同方向尚未确认的草稿；已确认的版本会保留。</p><div className="resume-review-actions"><button type="submit" disabled={busy||uncertain}>保存到待确认</button><button type="button" disabled={busy||uncertain} onClick={()=>setEditor(null)}>先不改了</button></div></form>}
 {confirm&&<section className="resume-review-confirmation"><h2>{confirm.action==='approve'?'确认这一版':confirm.action==='delete'?'移除这个版本':'确认这个选择'}</h2><p>{confirm.action==='approve'?'请核对完整原稿里的经历、数字和个人贡献。确认后这版可以用了，产品不会替你发送。':confirm.action==='delete'?'这个对象的原稿和历史正文都会移除，引用它的后续草稿可能需要重新核对。你另存的其他版本不会一起删除。':confirm.action==='decline'?'这份草稿不再继续，不会发出。':confirm.action==='archive'?'从可用版本里收起它，历史确认与原稿仍会保留。':'恢复为一个新的待确认版本，需要再核对并确认。'}</p><div className="resume-review-actions"><button type="button" disabled={busy||uncertain} onClick={decide}>{confirm.action==='approve'?'确认这一版':'确认这个选择'}</button><button type="button" disabled={busy||uncertain} onClick={()=>setConfirm(null)}>再核对一下</button></div></section>}
 {detail&&<article className="resume-review-detail"><h2>{detail.item.label} · v{detail.item.sequence}</h2><p>{labels[detail.item.track]} · {states[detail.item.status]}{detail.item.resumeStatus==='archived'?' · 已归档':''} · r{detail.item.revision}</p><p>{detail.item.source==='paste'?'你粘贴的原稿':'你从已确认版本另存并修改的草稿'} · 敏感资料</p>{detail.item.derivedFrom&&<p>来源版本：<a href={'/pending/'+detail.item.derivedFrom.pendingItemId}>查看原版</a></p>}<pre className="resume-review-copy">{detail.payload.text}</pre><div className="resume-review-actions">{detail.item.status==='pending'&&<><button type="button" disabled={busy||uncertain} onClick={()=>setConfirm({item:detail.item,action:'approve'})}>确认这一版</button><button type="button" disabled={busy||uncertain} onClick={()=>void open(detail.item.id,true)}>改一下</button><button type="button" disabled={busy||uncertain} onClick={()=>setConfirm({item:detail.item,action:'decline'})}>不要了</button></>}{detail.item.status==='approved'&&<><button type="button" onClick={()=>void copy()}>{copied?'已复制':'复制全文'}</button><button type="button" disabled={busy||uncertain} onClick={()=>void open(detail.item.id,false,true)}>另存一版再修改</button>{detail.item.resumeStatus==='active'&&<button type="button" disabled={busy||uncertain} onClick={()=>setConfirm({item:detail.item,action:'archive'})}>归档</button>}</>}{detail.item.status==='expired'&&<button type="button" disabled={busy||uncertain} onClick={()=>setConfirm({item:detail.item,action:'reopen'})}>恢复</button>}<button type="button" disabled={busy||uncertain} onClick={()=>setConfirm({item:detail.item,action:'delete'})}>移除</button><button type="button" onClick={()=>setDetail(null)}>收起正文</button></div></article>}
 <ul className="resume-review-list">{items.map(item=><li key={item.id}><h2><a href={'/pending/'+item.id}>{item.label} · v{item.sequence}</a></h2><p>{labels[item.track]} · <span className={'resume-state state-'+item.status}>{states[item.status]}</span>{item.resumeStatus==='archived'?' · 已归档':''}</p><p>r{item.revision} · {item.source==='paste'?'你粘贴的原稿':'本人另存的修改版'}</p><button type="button" disabled={busy||uncertain} onClick={()=>void open(item.id)}>查看完整内容</button></li>)}</ul>{next&&<button type="button" disabled={busy||uncertain} onClick={()=>void load(next)}>继续看版本</button>}
 </section></main>;
}
