import { careerRecordId,careerRecordObject } from './career-record-values.ts';
export const CAREER_EXPERIENCE_KINDS=Object.freeze(['course_project','independent_project','internship','employment','volunteering','other'] as const);
export const CAREER_STORY_TAGS=Object.freeze(['ownership','ambiguity','conflict','collaboration','problem_solving','leadership','learning','other'] as const);
export type CareerExperienceKind=typeof CAREER_EXPERIENCE_KINDS[number];
export type CareerStoryTag=typeof CAREER_STORY_TAGS[number];
export type CareerDataSensitivity='normal'|'sensitive'|'restricted';
export type CareerLibraryKind='project'|'story';
export type CareerLibraryAction='create'|'edit'|'confirm'|'withdraw'|'delete';
export interface CareerLibraryBase {readonly id:string;readonly ownerId:string;readonly revision:number;readonly createdAt:string;readonly updatedAt:string;readonly lastOperationId:string;readonly title:string;readonly experienceKind:CareerExperienceKind;readonly sensitivity:CareerDataSensitivity;readonly source:'user_entered';readonly confirmedAt:string|null;readonly confirmedRevision:number|null;}
export interface CareerProject extends CareerLibraryBase {readonly kind:'project';readonly subjectId:string;readonly referenceId:string;readonly occurredAt:string;readonly context:string;readonly contribution:string;readonly outcome:string;readonly state:'active'|'withdrawn';readonly verification:'self_reported'|'user_confirmed';}
export interface CareerStar {readonly situation:string;readonly task:string;readonly action:string;readonly result:string;}
export interface CareerStoryProjectRef {readonly id:string;readonly revision:number;}
export interface CareerStory extends CareerLibraryBase {readonly english:Readonly<CareerStar>;readonly chinese:Readonly<CareerStar>;readonly tags:readonly CareerStoryTag[];readonly projects:readonly Readonly<CareerStoryProjectRef>[];readonly status:'draft'|'confirmed';}
export type CareerLibraryRecord=CareerProject|CareerStory;
export interface CareerLibraryCommand {readonly operationId:string;readonly expectedRevision:number;readonly title?:string;readonly experienceKind?:CareerExperienceKind;readonly sensitivity?:CareerDataSensitivity;readonly occurredAt?:string;readonly context?:string;readonly contribution?:string;readonly outcome?:string;readonly english?:Readonly<CareerStar>;readonly chinese?:Readonly<CareerStar>;readonly tags?:readonly CareerStoryTag[];readonly projects?:readonly Readonly<CareerStoryProjectRef>[];}
export type CareerProjectSummary=Omit<CareerProject,'context'|'contribution'|'outcome'>;
export type CareerStorySummary=Omit<CareerStory,'english'|'chinese'>;
export type CareerStoryEvidenceAvailability='current'|'unconfirmed'|'stale'|'withdrawn'|'missing';
export interface CareerStoryView {readonly story:Readonly<CareerStory>;readonly evidenceAvailability:CareerStoryEvidenceAvailability;}
function fail():never{throw Error('The saved experience could not be confirmed.');}
export function careerLibraryText(value:unknown,max:number,multiline=false,empty=false){if(typeof value!=='string'||!empty&&!value.trim()||Array.from(value).length>max||/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f\u202a-\u202e\u2066-\u2069\ud800-\udfff]/u.test(value)||!multiline&&/[\r\n\t]/.test(value))return fail();return value;}
function integer(v:unknown,min=1){if(typeof v!=='number'||!Number.isSafeInteger(v)||Object.is(v,-0)||v<min||v>2147483647)return fail();return v;}
function choice<T extends string>(v:unknown,values:readonly T[]):T{if(typeof v!=='string'||!values.includes(v as T))return fail();return v as T;}
export function careerLibraryTime(v:unknown):string{if(typeof v!=='string'||!Number.isFinite(Date.parse(v))||new Date(v).toISOString()!==v)return fail();return v;}
function array(value:unknown,max:number){if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length>max)return fail();const d=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(d).length!==value.length+1)return fail();return Array.from({length:value.length},(_,i)=>{if(!d[i]||!('value' in d[i])||!d[i].enumerable)return fail();return d[i].value;});}
function star(value:unknown){const v=careerRecordObject(value,['situation','task','action','result']);return Object.freeze({situation:careerLibraryText(v.situation,4000,true,true),task:careerLibraryText(v.task,4000,true,true),action:careerLibraryText(v.action,4000,true,true),result:careerLibraryText(v.result,4000,true,true)});}
function tags(value:unknown){const result=array(value,8).map(v=>choice(v,CAREER_STORY_TAGS));if(new Set(result).size!==result.length)return fail();return Object.freeze(result);}
function projects(value:unknown){const result=array(value,10).map(item=>{const v=careerRecordObject(item,['id','revision']);return Object.freeze({id:careerRecordId(v.id),revision:integer(v.revision)});});if(new Set(result.map(v=>v.id)).size!==result.length)return fail();return Object.freeze(result);}
const commonFields=['title','experienceKind','sensitivity'] as const,projectFields=['occurredAt','context','contribution','outcome'] as const,storyFields=['english','chinese','tags','projects'] as const;
function common(v:Record<string,unknown>){return {title:careerLibraryText(v.title,200),experienceKind:choice(v.experienceKind,CAREER_EXPERIENCE_KINDS),sensitivity:choice(v.sensitivity,['normal','sensitive','restricted'] as const)};}
function body(kind:CareerLibraryKind,v:Record<string,unknown>){return {...common(v),...(kind==='project'?{occurredAt:careerLibraryTime(v.occurredAt),context:careerLibraryText(v.context,4000,true),contribution:careerLibraryText(v.contribution,4000,true,true),outcome:careerLibraryText(v.outcome,4000,true,true)}:{english:star(v.english),chinese:star(v.chinese),tags:tags(v.tags),projects:projects(v.projects)})};}
export function parseCareerLibraryCommand(kind:CareerLibraryKind,action:CareerLibraryAction,value:unknown):Readonly<CareerLibraryCommand>{
 if(!['project','story'].includes(kind)||!['create','edit','confirm','withdraw','delete'].includes(action)||kind==='story'&&action==='withdraw')return fail();const writes=action==='create'||action==='edit',fields=[...commonFields,...(kind==='project'?projectFields:storyFields)],v=careerRecordObject(value,['operationId','expectedRevision',...(writes?fields:[])]);
 const operationId=careerRecordId(v.operationId),expectedRevision=integer(v.expectedRevision,action==='create'?0:1);if(action==='create'&&expectedRevision!==0)return fail();return Object.freeze({operationId,expectedRevision,...(writes?body(kind,v):{})});
}
const baseFields=['id','ownerId','revision','createdAt','updatedAt','lastOperationId','source','confirmedAt','confirmedRevision',...commonFields];
function base(v:Record<string,unknown>):CareerLibraryBase{const createdAt=careerLibraryTime(v.createdAt),updatedAt=careerLibraryTime(v.updatedAt),revision=integer(v.revision);if(v.source!=='user_entered'||createdAt>updatedAt)return fail();const confirmedAt=v.confirmedAt===null?null:careerLibraryTime(v.confirmedAt),confirmedRevision=v.confirmedRevision===null?null:integer(v.confirmedRevision);if((confirmedAt===null)!==(confirmedRevision===null)||confirmedAt!==null&&(confirmedAt<createdAt||confirmedAt>updatedAt||confirmedRevision!>revision))return fail();return {id:careerRecordId(v.id),ownerId:careerRecordId(v.ownerId),revision,createdAt,updatedAt,lastOperationId:careerRecordId(v.lastOperationId),source:'user_entered',confirmedAt,confirmedRevision,...common(v)};}
export function parseCareerProject(value:unknown):Readonly<CareerProject>{const v=careerRecordObject(value,[...baseFields,...projectFields,'kind','subjectId','referenceId','state','verification']),b=base(v);const fields=body('project',v) as Pick<CareerProject,'occurredAt'|'context'|'contribution'|'outcome'>;
 if(v.kind!=='project'||v.subjectId!==b.id||v.referenceId!=='career-project:'+b.id+':'+b.revision)return fail();const state=choice(v.state,['active','withdrawn'] as const),verification=choice(v.verification,['self_reported','user_confirmed'] as const);
 if(verification==='self_reported'&&b.confirmedAt!==null||verification==='user_confirmed'&&(b.confirmedAt===null||state==='active'&&(b.confirmedRevision!==b.revision||b.confirmedAt!==b.updatedAt)))return fail();return Object.freeze({...b,...fields,kind:'project',subjectId:b.id,referenceId:v.referenceId as string,state,verification});
}
export function parseCareerStory(value:unknown):Readonly<CareerStory>{const v=careerRecordObject(value,[...baseFields,...storyFields,'status']),b=base(v),fields=body('story',v) as Pick<CareerStory,'english'|'chinese'|'tags'|'projects'>,status=choice(v.status,['draft','confirmed'] as const);
 if(status==='draft'&&b.confirmedAt!==null||status==='confirmed'&&(b.confirmedAt!==b.updatedAt||b.confirmedRevision!==b.revision||Object.values(fields.english).some(v=>!v.trim())))return fail();return Object.freeze({...b,...fields,status});
}
export function careerLibrarySummary(kind:CareerLibraryKind,record:CareerLibraryRecord):Readonly<CareerProjectSummary|CareerStorySummary>{if(kind==='project'){const {context,contribution,outcome,...summary}=record as CareerProject;return Object.freeze(summary);}const {english,chinese,...summary}=record as CareerStory;return Object.freeze(summary);}
export function parseCareerLibrarySummary(kind:CareerLibraryKind,value:unknown):Readonly<CareerProjectSummary|CareerStorySummary>{
 const fields=kind==='project'?['kind','subjectId','referenceId','occurredAt','state','verification']:['tags','projects','status'],v=careerRecordObject(value,[...baseFields,...fields]),b=base(v);
 if(kind==='project'){if(v.kind!=='project'||v.subjectId!==b.id||v.referenceId!=='career-project:'+b.id+':'+b.revision)return fail();const state=choice(v.state,['active','withdrawn'] as const),verification=choice(v.verification,['self_reported','user_confirmed'] as const);if(verification==='self_reported'&&b.confirmedAt!==null||verification==='user_confirmed'&&(b.confirmedAt===null||state==='active'&&(b.confirmedRevision!==b.revision||b.confirmedAt!==b.updatedAt)))return fail();return Object.freeze({...b,kind:'project',subjectId:b.id,referenceId:v.referenceId as string,occurredAt:careerLibraryTime(v.occurredAt),state,verification});}
 const status=choice(v.status,['draft','confirmed'] as const);if(status==='draft'&&b.confirmedAt!==null||status==='confirmed'&&(b.confirmedAt!==b.updatedAt||b.confirmedRevision!==b.revision))return fail();return Object.freeze({...b,tags:tags(v.tags),projects:projects(v.projects),status});
}
