import {careerRecordObject as object,careerRecordId as id,CareerRecordInputError} from './career-record-values.ts';
export type DailyItemState='proposed'|'accepted'|'done'|'moved'|'dropped';
export interface DailyPlanItem {readonly id:string;readonly candidateId:string;readonly title:string;readonly minutes:number;readonly rule:'user';readonly state:DailyItemState;readonly completedAt:string|null;readonly completionSource:'self_reported'|null;readonly movedTo:Readonly<{localDate:string;planId:string;itemId:string}>|null;}
export interface DailyPlan {readonly id:string;readonly ownerId:string;readonly companionId:string;readonly localDate:string;readonly timeZone:string;readonly generatedBy:'rules';readonly briefMessageId:null;readonly acceptedAt:string|null;readonly revision:number;readonly createdAt:string;readonly updatedAt:string;readonly lastOperationId:string;readonly items:readonly Readonly<DailyPlanItem>[];}
export interface DailyPlanView {readonly ownerId:string;readonly companionId:string;readonly localDate:string;readonly timeZone:string;readonly dailyMinutes:number;readonly paused:boolean;readonly automaticStatus:'not_available';readonly plan:Readonly<DailyPlan>|null;}
export type DailyPlanCommand={readonly operationId:string;readonly companionId:string;readonly localDate:string;readonly planId:string|null;readonly expectedRevision:number}&({readonly action:'add';readonly title:string;readonly minutes:number}|{readonly action:'edit';readonly itemId:string;readonly title:string;readonly minutes:number}|{readonly action:'accept'}|{readonly action:'done'|'move'|'drop';readonly itemId:string});
export interface DailyPlanResult {readonly view:Readonly<DailyPlanView>;readonly operation:Readonly<{id:string;action:DailyPlanCommand['action'];localDate:string;planId:string;appliedRevision:number;replayed:boolean}>;}
const fail=():never=>{throw new CareerRecordInputError();};
const integer=(x:unknown,min:number,max:number):number=>{if(typeof x!=='number'||!Number.isSafeInteger(x)||Object.is(x,-0)||x<min||x>max)return fail();return x;};
export function dailyDate(v:unknown):string{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00.000Z'))||new Date(v+'T00:00:00.000Z').toISOString().slice(0,10)!==v)return fail();return v;}
function instant(v:unknown):string{if(typeof v!=='string'||!Number.isFinite(Date.parse(v))||new Date(v).toISOString()!==v)return fail();return v;}
function zone(v:unknown):string{if(typeof v!=='string'||v.length>100)return fail();try{new Intl.DateTimeFormat('en-US',{timeZone:v}).format(0);}catch{return fail();}return v;}
function title(v:unknown):string{if(typeof v!=='string'||v.length<1||v.length>160||v.trim()!==v||/[\x00-\x1f\x7f\u202a-\u202e\u2066-\u2069]/.test(v))return fail();return v;}
function item(value:unknown):Readonly<DailyPlanItem>{const v=object(value,['id','candidateId','title','minutes','rule','state','completedAt','completionSource','movedTo']);
 if(v.rule!=='user'||!['proposed','accepted','done','moved','dropped'].includes(v.state as string))return fail();
 const completedAt=v.completedAt===null?null:instant(v.completedAt);if((v.state==='done')!==(completedAt!==null)||v.completionSource!==(v.state==='done'?'self_reported':null))return fail();
 let movedTo:DailyPlanItem['movedTo']=null;if(v.movedTo!==null){const m=object(v.movedTo,['localDate','planId','itemId']);movedTo=Object.freeze({localDate:dailyDate(m.localDate),planId:id(m.planId),itemId:id(m.itemId)});}if((v.state==='moved')!==(movedTo!==null))return fail();
 return Object.freeze({id:id(v.id),candidateId:id(v.candidateId),title:title(v.title),minutes:integer(v.minutes,1,1440),rule:'user',state:v.state as DailyItemState,completedAt,completionSource:v.completionSource as DailyPlanItem['completionSource'],movedTo});}
export function parseDailyPlan(value:unknown):Readonly<DailyPlan>{const v=object(value,['id','ownerId','companionId','localDate','timeZone','generatedBy','briefMessageId','acceptedAt','revision','createdAt','updatedAt','lastOperationId','items']);
 if(v.generatedBy!=='rules'||v.briefMessageId!==null||!Array.isArray(v.items)||Object.getPrototypeOf(v.items)!==Array.prototype||v.items.length>50)return fail();
 const ds=Object.getOwnPropertyDescriptors(v.items);if(Reflect.ownKeys(ds).length!==v.items.length+1)return fail();const items:Readonly<DailyPlanItem>[]=[];for(let i=0;i<v.items.length;i++){if(!ds[i]||!('value'in ds[i])||!ds[i].enumerable)return fail();items.push(item(ds[i].value));}
 if(new Set(items.map(x=>x.id)).size!==items.length||new Set(items.map(x=>x.candidateId)).size!==items.length)return fail();
 const acceptedAt=v.acceptedAt===null?null:instant(v.acceptedAt);if(!acceptedAt&&items.some(x=>x.state!=='proposed'))return fail();
 return Object.freeze({id:id(v.id),ownerId:id(v.ownerId),companionId:id(v.companionId),localDate:dailyDate(v.localDate),timeZone:zone(v.timeZone),generatedBy:'rules',briefMessageId:null,acceptedAt,revision:integer(v.revision,1,2147483647),createdAt:instant(v.createdAt),updatedAt:instant(v.updatedAt),lastOperationId:id(v.lastOperationId),items:Object.freeze(items)});}
export function parseDailyPlanCommand(value:unknown):Readonly<DailyPlanCommand>{const base=['operationId','companionId','localDate','planId','expectedRevision','action'];const v=object(value,base,['title','minutes','itemId']);
 const c={operationId:id(v.operationId),companionId:id(v.companionId),localDate:dailyDate(v.localDate),planId:v.planId===null?null:id(v.planId),expectedRevision:integer(v.expectedRevision,0,2147483646)};if((c.planId===null)!==(c.expectedRevision===0))return fail();
 if(v.action==='add'){object(value,[...base,'title','minutes']);return Object.freeze({...c,action:'add',title:title(v.title),minutes:integer(v.minutes,1,1440)});}
 if(v.action==='edit'){object(value,[...base,'itemId','title','minutes']);if(!c.planId)return fail();return Object.freeze({...c,action:'edit',itemId:id(v.itemId),title:title(v.title),minutes:integer(v.minutes,1,1440)});}
 if(v.action==='accept'){object(value,base);if(!c.planId)return fail();return Object.freeze({...c,action:'accept'});}
 object(value,[...base,'itemId']);if(!c.planId||!['done','move','drop'].includes(v.action as string))return fail();return Object.freeze({...c,action:v.action as 'done'|'move'|'drop',itemId:id(v.itemId)});
}
export function parseDailyPlanView(value:unknown):Readonly<DailyPlanView>{const v=object(value,['ownerId','companionId','localDate','timeZone','dailyMinutes','paused','automaticStatus','plan']);if(typeof v.paused!=='boolean'||v.automaticStatus!=='not_available')return fail();const ownerId=id(v.ownerId),companionId=id(v.companionId),localDate=dailyDate(v.localDate),plan=v.plan===null?null:parseDailyPlan(v.plan);if(plan&&(v.paused||plan.ownerId!==ownerId||plan.companionId!==companionId||plan.localDate!==localDate))return fail();return Object.freeze({ownerId,companionId,localDate,timeZone:zone(v.timeZone),dailyMinutes:integer(v.dailyMinutes,0,1440),paused:v.paused,automaticStatus:'not_available',plan});}
