import { before,after,test } from 'node:test';import assert from 'node:assert/strict';import { randomUUID } from 'node:crypto';import { readFile } from 'node:fs/promises';
import { careerProgress } from '@companion/career-core';import type { CareerProject,CareerStory } from '@companion/platform-contracts';
import { CareerStories } from '../src/career-stories.ts';import { ApiError } from '../src/errors.ts';import { FICTIONAL_LEGAL } from './fixtures/student-entry.ts';import { createCompanionNameSafetyFixture } from './fixtures/companion-name-safety.ts';
let f:Awaited<ReturnType<typeof createCompanionNameSafetyFixture>>,library:CareerStories;
before(async()=>{f=await createCompanionNameSafetyFixture();library=new CareerStories(f.db,f.config,FICTIONAL_LEGAL);});after(async()=>{await f?.close();});
const project=(patch:Record<string,unknown>={})=>({operationId:randomUUID(),expectedRevision:0,title:'Fictional course project',experienceKind:'course_project',sensitivity:'normal',occurredAt:'2026-08-01T00:00:00.000Z',context:'Fictional team research assignment.',contribution:'Fictional individual source comparison.',outcome:'Professor commented on the comparison; no award claimed.',...patch});
const english={situation:'Fictional strategy course.',task:'Compare evidence.',action:'Compared sources and checked assumptions.',result:'Fictional positive feedback; no award or made-up metric.'};
const story=(patch:Record<string,unknown>={})=>({operationId:randomUUID(),expectedRevision:0,title:'Fictional course story',experienceKind:'course_project',sensitivity:'normal',english,chinese:{situation:'虚构课程',task:'虚构任务',action:'虚构个人行动',result:'虚构反馈'},tags:['ownership'],projects:[],...patch});
const action=(revision:number)=>({operationId:randomUUID(),expectedRevision:revision}),error=(status:number)=>(e:unknown)=>e instanceof ApiError&&e.status===status;
test('actual owner project and story flow distinguishes personal confirmation, invalidates edited confirmation, and derives only real ledger progress',async()=>{
 const who=await f.actor(),p=(await library.mutate(who,'project','create',null,project())).record as CareerProject;assert.equal(p.verification,'self_reported');assert.equal((await library.progress(who)).progress.provisionalCounts.project,1);assert.equal((await library.progress(who)).progress.counts.project,0);
 const s=(await library.mutate(who,'story','create',null,story({projects:[{id:p.id,revision:1}]}))).record as CareerStory;assert.equal(s.status,'draft');await assert.rejects(library.mutate(who,'story','confirm',s.id,action(1)),error(409));
 const confirmed=(await library.mutate(who,'project','confirm',p.id,action(1))).record as CareerProject;assert.equal(confirmed.verification,'user_confirmed');assert.equal(confirmed.confirmedRevision,2);assert.deepEqual((await library.progress(who)).progress,careerProgress(who.userId,[confirmed]));assert.deepEqual((await library.progress(who)).coverage,['project']);
 await library.mutate(who,'story','edit',s.id,story({expectedRevision:1,projects:[{id:p.id,revision:2}]}));const confirmedStory=(await library.mutate(who,'story','confirm',s.id,action(2))).record as CareerStory;assert.equal(confirmedStory.status,'confirmed');assert.equal(confirmedStory.confirmedRevision,3);
 const edited=(await library.mutate(who,'story','edit',s.id,story({expectedRevision:3,projects:[{id:p.id,revision:2}],english:{...english,result:'Fictional revised result.'}}))).record as CareerStory;assert.equal(edited.status,'draft');assert.equal(edited.confirmedAt,null);
 await library.mutate(who,'project','edit',p.id,project({expectedRevision:2,contribution:'Fictional corrected individual action.'}));assert.equal((await library.get(who,'story',s.id)).evidenceAvailability,'stale');assert.equal((await library.progress(who)).progress.counts.project,0);
});
test('source labels, privacy, ownership and genuine project revisions govern links; withdrawal/deletion invalidates current evidence without rewriting story status',async()=>{
 const who=await f.actor(),other=await f.actor(),p=(await library.mutate(who,'project','create',null,project({sensitivity:'restricted'}))).record as CareerProject;await library.mutate(who,'project','confirm',p.id,action(1));
 await assert.rejects(library.mutate(who,'story','create',null,story({projects:[{id:p.id,revision:2}]})),error(400));await assert.rejects(library.mutate(who,'story','create',null,story({sensitivity:'restricted',experienceKind:'employment',projects:[{id:p.id,revision:2}]})),error(400));await assert.rejects(library.mutate(other,'story','create',null,story({sensitivity:'restricted',projects:[{id:p.id,revision:2}]})),error(404));
 const s=(await library.mutate(who,'story','create',null,story({sensitivity:'restricted',projects:[{id:p.id,revision:2}]}))).record as CareerStory;await library.mutate(who,'story','confirm',s.id,action(1));await library.mutate(who,'project','withdraw',p.id,action(2));const view=await library.get(who,'story',s.id);assert.equal((view.record as CareerStory).status,'confirmed');assert.equal(view.evidenceAvailability,'withdrawn');assert.equal((await library.progress(who)).progress.counts.project,0);
 await library.mutate(who,'project','delete',p.id,action(3));assert.equal((await library.get(who,'story',s.id)).evidenceAvailability,'missing');await assert.rejects(library.mutate(who,'story','confirm',s.id,action(2)),error(404));
});
test('body is encrypted, shared operation IDs cannot switch domain or content, and physical forgetting cannot be reversed by a late create',async()=>{
 const who=await f.actor(),command=story(),saved=await library.mutate(who,'story','create',null,command),id=saved.record!.id,row=(await f.db.query('SELECT * FROM platform_career_stories WHERE id=$1',[id])).rows[0];for(const text of [command.title,command.english.action,command.chinese.result])assert(!row.record_ciphertext.includes(Buffer.from(text)));
 assert.equal((await library.mutate(who,'story','create',null,command)).operation.replayed,true);await assert.rejects(library.mutate(who,'project','create',null,project({operationId:command.operationId})),error(409));await assert.rejects(library.mutate(who,'story','create',null,{...command,title:'Fictional conflicting body'}),error(409));
 await library.mutate(who,'story','delete',id,action(1));assert.equal((await library.mutate(who,'story','create',null,command)).record,null);await assert.rejects(library.get(who,'story',id),error(404));
 await f.db.query('INSERT INTO platform_career_stories(id,user_id,status,sensitivity,revision,last_operation_id,record_ciphertext,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[row.id,row.user_id,row.status,row.sensitivity,row.revision,row.last_operation_id,row.record_ciphertext,row.created_at,row.updated_at]);await assert.rejects(library.get(who,'story',id),error(503));
 for(const receipt of (await f.db.query('SELECT * FROM platform_career_library_operations WHERE user_id=$1',[who.userId])).rows){const raw=f.crypto.openUtf8(receipt.receipt_ciphertext,{table:'platform_career_library_operations',column:'receipt_ciphertext',rowId:receipt.operation_id,ownerId:who.userId,revision:receipt.applied_revision});assert(!raw.includes('Fictional'));}
});
test('actual confirmation history rejects valid older ciphertext and metadata changes; concurrent edits accept one real version',async()=>{
 const who=await f.actor(),s=(await library.mutate(who,'story','create',null,story())).record as CareerStory,row=(await f.db.query('SELECT * FROM platform_career_stories WHERE id=$1',[s.id])).rows[0];await library.mutate(who,'story','confirm',s.id,action(1));
 await f.db.query('UPDATE platform_career_stories SET revision=$2,status=$3,last_operation_id=$4,record_ciphertext=$5,updated_at=$6 WHERE id=$1',[s.id,row.revision,row.status,row.last_operation_id,row.record_ciphertext,row.updated_at]);await assert.rejects(library.get(who,'story',s.id),error(503));await assert.rejects(f.db.query('DELETE FROM platform_career_library_operations WHERE user_id=$1',[who.userId]));
 const other=await f.actor(),p=(await library.mutate(other,'project','create',null,project())).record as CareerProject;const results=await Promise.allSettled(['Fictional A','Fictional B'].map(title=>library.mutate(other,'project','edit',p.id,project({expectedRevision:1,title}))));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await library.get(other,'project',p.id)).record.revision,2);
});
test('private reads, withdrawal and deletion survive withdrawn admission; foreign/staff/revoked sessions cannot access owner records',async()=>{
 const who=await f.actor(),other=await f.actor(),staff=await f.actor(true),p=(await library.mutate(who,'project','create',null,project())).record as CareerProject,s=(await library.mutate(who,'story','create',null,story())).record as CareerStory;
 for(const [kind,id] of [['project',p.id],['story',s.id]] as const){await assert.rejects(library.get(other,kind,id),error(404));await assert.rejects(library.mutate(other,kind,'delete',id,action(1)),error(404));await assert.rejects(library.get(staff,kind,id),error(403));}
 await f.db.query('DELETE FROM platform_terms_consents WHERE user_id=$1',[who.userId]);await f.db.query('UPDATE platform_users SET email_verified_at=NULL WHERE id=$1',[who.userId]);assert.equal((await library.get(who,'story',s.id)).record.id,s.id);await assert.rejects(library.mutate(who,'story','confirm',s.id,action(1)),error(403));await library.mutate(who,'project','withdraw',p.id,action(1));await library.mutate(who,'story','delete',s.id,action(1));
 await f.db.query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[who.userId]);await assert.rejects(library.get(who,'project',p.id),error(401));
});
test('owner paging excludes foreign cursors and raw STAR/facts, incomplete stories cannot confirm, and genuine account deletion cascades',async()=>{
 const who=await f.actor(),other=await f.actor();for(let i=0;i<53;i++)await library.mutate(who,'story','create',null,story({title:'Fictional story '+i}));const first=await library.list(who,'story');assert.equal(first.records.length,50);assert(first.nextAfter);const second=await library.list(who,'story',{after:first.nextAfter});assert.equal(second.records.length,3);assert.equal(second.nextAfter,null);assert(!('english' in first.records[0].record));await assert.rejects(library.list(other,'story',{after:first.nextAfter}),error(404));
 const partial=(await library.mutate(other,'story','create',null,story({english:{...english,result:''}}))).record as CareerStory;await assert.rejects(library.mutate(other,'story','confirm',partial.id,action(1)),error(400));
 await library.mutate(who,'project','create',null,project());await f.db.query('DELETE FROM platform_users WHERE id=$1',[who.userId]);for(const table of ['platform_career_evidence','platform_career_stories','platform_career_library_operations'])assert.equal((await f.db.query('SELECT user_id FROM '+table+' WHERE user_id=$1',[who.userId])).rowCount,0);await f.db.migrate();await f.db.query(await readFile(new URL('../migrations/057_career_story_library.sql',import.meta.url),'utf8'));
});
test('late actual session reset rolls back a story and its new receipt together',async()=>{
 const who=await f.actor(),original=f.db.withBoundedTransaction.bind(f.db);f.db.withBoundedTransaction=async(run,options)=>original(async client=>{const query=client.query.bind(client);let reset=false;const guarded=new Proxy(client,{get(target,key){if(key==='query')return async(...args:any[])=>{const r=await (query as any)(...args);if(!reset&&typeof args[0]==='string'&&args[0].startsWith('INSERT INTO platform_career_stories')){reset=true;await query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[who.userId]);}return r;};return Reflect.get(target,key);}});return run(guarded);},options);
 try{await assert.rejects(library.mutate(who,'story','create',null,story()),error(401));}finally{f.db.withBoundedTransaction=original;}for(const table of ['platform_career_stories','platform_career_library_operations'])assert.equal((await f.db.query('SELECT user_id FROM '+table+' WHERE user_id=$1',[who.userId])).rowCount,0);
});

test('withdrawal time is an authentic immutable operation time, survives later edits, and cannot be replaced by a SQL timestamp or review',async()=>{
 const who=await f.actor(),p=(await library.mutate(who,'project','create',null,project())).record as CareerProject;await library.mutate(who,'project','withdraw',p.id,action(1));const row=(await f.db.query('SELECT * FROM platform_career_evidence WHERE id=$1',[p.id])).rows[0];const op=(await f.db.query("SELECT * FROM platform_career_library_operations WHERE record_id=$1 AND action='withdraw'",[p.id])).rows[0];assert.equal(row.withdrawn_at.toISOString(),op.created_at.toISOString());assert.equal(row.mentor_review,null);
 await library.mutate(who,'project','edit',p.id,project({expectedRevision:2,title:'Fictional corrected withdrawn title'}));const edited=(await f.db.query('SELECT * FROM platform_career_evidence WHERE id=$1',[p.id])).rows[0];assert.equal(edited.withdrawn_at.toISOString(),row.withdrawn_at.toISOString());assert.equal((await library.get(who,'project',p.id)).record.revision,3);await assert.rejects(f.db.query('UPDATE platform_career_evidence SET mentor_review=$2 WHERE id=$1',[p.id,{reviewerId:who.userId}]));
 await f.db.query("UPDATE platform_career_evidence SET withdrawn_at=withdrawn_at+interval '1 second' WHERE id=$1",[p.id]);await assert.rejects(library.get(who,'project',p.id),error(503));
});
