import { before, after, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createProviderRuntime } from '@companion/ai-core';
import { PLATFORM_ACCOUNT_HEADER } from '@companion/platform-contracts';
import { buildApp } from '../src/app.ts';
import { readConfig } from '../src/config.ts';
import { hashPassword } from '../src/auth.ts';
import { createPrebirthFixture, withPrebirthLoopback, type PrebirthFixture } from './fixtures/companion-prebirth.ts';
import { readyBirth } from './fixtures/companion-birth.ts';
import { FICTIONAL_LEGAL } from './fixtures/student-entry.ts';
const origin = 'https://fictional-daily-settings.example.invalid', prefix = '/api/platform/companion/settings/daily', password = 'Fictional-settings-password-123';
let f: PrebirthFixture, system: Awaited<ReturnType<typeof buildApp>>, calls = 0;
before(async () => { f = await createPrebirthFixture(); system = await buildApp({ db: f.db, config: { ...readConfig(), dataCrypto: f.crypto, requireVerifiedEmail: true, allowedOrigins: new Set([origin]) }, legalBundle: FICTIONAL_LEGAL, enableQueue: false, runtime: createProviderRuntime({ env: { PLATFORM_ALLOW_PROVIDER_CALLS: '0' }, fetch: async () => { calls++; throw Error('No external call'); } }) }); });
after(async () => { await system?.app.close(); assert.equal(calls, 0); await f?.close(); });
async function login(owner: string) { const r = await system.app.inject({ method: 'POST', url: '/api/platform/auth/login', headers: { origin }, payload: { email: owner + '@example.invalid', password } }); assert.equal(r.statusCode, 200, r.body); const raw = r.headers['set-cookie']; return { origin, cookie: (Array.isArray(raw) ? raw[0] : raw)!.split(';')[0], [PLATFORM_ACCOUNT_HEADER]: owner }; }
test('actual authenticated HTTP saves a real companion preference, survives new login and protects operation observation', async () => {
    const who = await f.actor();
    await f.db.query('UPDATE platform_users SET password_hash=$2 WHERE id=$1', [who.userId, await hashPassword(password)]);
    let headers = await login(who.userId);
    assert.equal((await system.app.inject({ url: prefix, headers })).statusCode, 409);
    await withPrebirthLoopback(async (runtime) => { const b = await readyBirth(f, runtime, { who }); await b.service.birth(who, b.body, b.key); });
    const current = await system.app.inject({ url: prefix, headers });
    assert.equal(current.statusCode, 200, current.body);
    assert.equal(current.headers['cache-control'], 'private, no-store');
    const state = current.json().settings;
    const body = { companionId: state.companionId, operationId: randomUUID(), expectedRevision: 0, preferences: { timeZone: 'America/New_York', morningTime: '09:00', quietStart: '22:30', quietEnd: '08:30', dailyMinutes: 90, webAlert: 'none' } };
    const saved = await system.app.inject({ method: 'PATCH', url: prefix, headers, payload: body });
    assert.equal(saved.statusCode, 200, saved.body);
    assert.equal(saved.json().settings.preferences.timeZone, 'America/New_York');
    headers = await login(who.userId);
    assert.equal((await system.app.inject({ url: prefix, headers })).json().settings.preferences.timeZone, 'America/New_York');
    const observed = await system.app.inject({ url: prefix + '/operations/' + body.operationId, headers });
    assert.equal(observed.statusCode, 200, observed.body);
    assert.equal(observed.json().operation.replayed, true);
    assert.equal((await system.app.inject({ method: 'PATCH', url: prefix, headers, payload: body })).json().operation.replayed, true);
    assert.equal((await system.app.inject({ url: prefix })).statusCode, 401);
    assert.equal((await system.app.inject({ url: prefix, headers: { ...headers, [PLATFORM_ACCOUNT_HEADER]: randomUUID() } })).statusCode, 409);
    assert.equal((await system.app.inject({ method: 'PATCH', url: prefix, headers: { ...headers, origin: 'https://foreign.invalid' }, payload: body })).statusCode, 403);
    for (const extra of [{ ownerId: who.userId }, { confirmed: true }, { provider: 'fictional' }])
        assert.equal((await system.app.inject({ method: 'PATCH', url: prefix, headers, payload: { ...body, ...extra } })).statusCode, 400);
    assert.equal((await system.app.inject({ url: prefix + '?owner=' + who.userId, headers })).statusCode, 400);
    assert.equal((await system.app.inject({ url: prefix + '/operations/' + randomUUID(), headers })).statusCode, 404);
});
