import {before,after,test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {DailyPlans} from '../src/daily-plans.ts';import {TodayRestService} from '../src/today-rest.ts';import {CompanionDailySettingsService} from '../src/companion-daily-settings.ts';
import {createPrebirthFixture,withPrebirthLoopback,type PrebirthFixture} from './fixtures/companion-prebirth.ts';import {readyBirth} from './fixtures/companion-birth.ts';import {FICTIONAL_LEGAL} from './fixtures/student-entry.ts';import {ApiError} from '../src/errors.ts';import {AccountCoreExport} from '../src/account-core-export.ts';import {AccountReauthentication} from '../src/account-reauthentication.ts';import {hashPassword} from '../src/auth.ts';import type {DailyPlanView} from '@companion/platform-contracts';
let f:PrebirthFixture,service:DailyPlans,daily:CompanionDailySettingsService,rest:TodayRestService;
before(async()=>{f=await createPrebirthFixture();service=new DailyPlans(f.db,f.config,FICTIONAL_LEGAL);daily=new CompanionDailySettingsService(f.db,f.config,FICTIONAL_LEGAL);rest=new TodayRestService(f.db,f.config,FICTIONAL_LEGAL);});after(async()=>{await f?.close();});
const error=(status:number)=>(e:unknown)=>e instanceof ApiError&&e.status===status;
const preferences={timeZone:'America/New_York',morningTime:'09:00',quietStart:'22:30',quietEnd:'08:30',dailyMinutes:90,webAlert:'none' as const};
async function born(){let who!:Awaited<ReturnType<PrebirthFixture['actor']>>;await withPrebirthLoopback(async runtime=>{const b=await readyBirth(f,runtime);who=b.ready.who;await b.service.birth(who,b.body,b.key);});const companionId=(await daily.read(who)).settings.companionId;await daily.change(who,{companionId,operationId:randomUUID(),expectedRevision:0,preferences});return who;}
const command=(view:Readonly<DailyPlanView>,extra:Record<string,unknown>)=>({operationId:randomUUID(),companionId:view.companionId,localDate:view.localDate,planId:view.plan?.id??null,expectedRevision:view.plan?.revision??0,...extra});
const add=(view:Readonly<DailyPlanView>,minutes=15)=>command(view,{action:'add',title:'PRIVATE_FICTIONAL_OWN_TASK',minutes});
async function clock(at:string,run:()=>Promise<void>){const original=f.db.withBoundedTransaction.bind(f.db);f.db.withBoundedTransaction=async(fn,options)=>original(c=>fn(new Proxy(c,{get(target,key){if(key==='query')return async(sql:any,...args:any[])=>sql==='SELECT clock_timestamp() at'?{rows:[{at:new Date(at)}]}:(target.query as any)(sql,...args);const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}})),options);try{await run();}finally{f.db.withBoundedTransaction=original;}}
test('owner adds, accepts and reports completion without generating evidence or pretending automatic tasks exist',async()=>{
 const who=await born(),initial=await service.read(who);assert.equal(initial.plan,null);assert.equal(initial.automaticStatus,'not_available');
 const cmd=add(initial),saved=await service.mutate(who,cmd);let v=saved.view;assert.equal(v.plan!.items[0].state,'proposed');assert.equal(v.plan!.items[0].rule,'user');assert.equal(v.plan!.briefMessageId,null);
 await assert.rejects(service.mutate(who,command(v,{action:'done',itemId:v.plan!.items[0].id})),error(409));
 v=(await service.mutate(who,command(v,{action:'accept'}))).view;assert(v.plan!.acceptedAt);const done=command(v,{action:'done',itemId:v.plan!.items[0].id});v=(await service.mutate(who,done)).view;
 assert.equal(v.plan!.items[0].state,'done');assert.equal(v.plan!.items[0].completionSource,'self_reported');assert(v.plan!.items[0].completedAt);
 assert.deepEqual(await new DailyPlans(f.db,f.config,FICTIONAL_LEGAL).read(who),v);assert.equal((await service.mutate(who,cmd)).view.plan!.revision,3);assert.equal((await service.observe(who,done.operationId)).operation.replayed,true);
 await assert.rejects(service.mutate(who,{...cmd,title:'Different fictional task'}),error(409));assert.equal((await f.db.query('SELECT * FROM platform_daily_plan_items WHERE user_id=$1',[who.userId])).rowCount,1);
});
test('moving is an atomic two-day saved operation, replay survives midnight, and history comes from real states',async()=>{
 const who=await born();let moved:any,itemId='',candidateId='';
 await clock('2026-10-31T16:00:00.000Z',async()=>{let v=(await service.mutate(who,add(await service.read(who)))).view;v=(await service.mutate(who,command(v,{action:'accept'}))).view;itemId=v.plan!.items[0].id;candidateId=v.plan!.items[0].candidateId;moved=command(v,{action:'move',itemId});v=(await service.mutate(who,moved)).view;assert.equal(v.plan!.items[0].state,'moved');assert.equal(v.plan!.items[0].movedTo!.localDate,'2026-11-01');assert.equal((await service.mutate(who,moved)).view.plan!.revision,3);});
 await clock('2026-11-01T17:00:00.000Z',async()=>{let v=await service.read(who);assert.equal(v.localDate,'2026-11-01');assert.equal(v.plan!.items.length,1);assert.notEqual(v.plan!.items[0].id,itemId);assert.equal(v.plan!.items[0].candidateId,candidateId);assert.equal(v.plan!.items[0].state,'proposed');assert.equal(v.plan!.acceptedAt,null);const replay=await service.mutate(who,moved);assert.equal(replay.view.localDate,'2026-11-01');assert.equal(replay.operation.localDate,'2026-10-31');assert.equal(replay.operation.replayed,true);
  const h=await f.db.withBoundedTransaction(c=>service.readHistoryInTransaction(c,who,'2026-11-01T17:00:00.000Z','America/New_York'));assert.deepEqual(h.historyDates,['2026-10-31','2026-10-30']);assert.deepEqual(h.history,[{candidateId,ownerId:who.userId,localDate:'2026-10-31',outcome:'dropped'}]);
  v=(await service.mutate(who,command(v,{action:'accept'}))).view;v=(await service.mutate(who,command(v,{action:'drop',itemId:v.plan!.items[0].id}))).view;assert.equal(v.plan!.items[0].state,'dropped');assert.equal(v.plan!.items[0].completionSource,null);
 });
});
test('daily budget and a full tomorrow roll back source state, target item and operation together',async()=>{
 const who=await born();await clock('2026-11-02T17:00:00.000Z',async()=>{await service.mutate(who,add(await service.read(who),90));});
 await clock('2026-11-01T17:00:00.000Z',async()=>{let v=await service.read(who);await assert.rejects(service.mutate(who,add(v,91)),error(409));assert.equal((await service.read(who)).plan,null);v=(await service.mutate(who,add(v,15))).view;v=(await service.mutate(who,command(v,{action:'accept'}))).view;const cmd=command(v,{action:'move',itemId:v.plan!.items[0].id});await assert.rejects(service.mutate(who,cmd),error(409));assert.deepEqual(await service.read(who),v);await assert.rejects(service.observe(who,cmd.operationId),error(404));});
 assert.equal((await f.db.query('SELECT * FROM platform_daily_plan_items WHERE user_id=$1',[who.userId])).rowCount,2);
});
test('rest conceals task content and blocks new actions while original operations and private history remain recoverable',async()=>{
 const who=await born(),cmd=add(await service.read(who)),saved=await service.mutate(who,cmd);await rest.change(who,{companionId:saved.view.companionId,operationId:randomUUID(),expectedRevision:0,choice:'1_day'});
 const hidden=await service.read(who);assert.equal(hidden.paused,true);assert.equal(hidden.plan,null);assert(!JSON.stringify(hidden).includes('PRIVATE_FICTIONAL'));await assert.rejects(service.mutate(who,command(saved.view,{action:'accept'})),error(409));assert.equal((await service.mutate(who,cmd)).view.plan,null);
 await f.db.query('DELETE FROM platform_terms_consents WHERE user_id=$1',[who.userId]);assert.equal((await service.observe(who,cmd.operationId)).operation.replayed,true);assert.equal((await service.read(who)).paused,true);
});
test('concurrent devices, forged coordinates, stale local dates and revoked identities cannot write another plan',async()=>{
 const who=await born(),view=await service.read(who),other=await born();const results=await Promise.allSettled([service.mutate(who,add(view)),service.mutate(who,add(view))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);
 await assert.rejects(service.mutate(other,add(view)),error(409));await assert.rejects(service.read(await f.actor()),error(409));await assert.rejects(service.read(await f.actor(true)),error(403));
 let stale:any;await clock('2026-11-03T04:59:59.999Z',async()=>{stale=add(await service.read(who));});await clock('2026-11-03T05:00:00.000Z',async()=>{await assert.rejects(service.mutate(who,stale),error(409));});
 const current=await service.read(who);await assert.rejects(service.mutate(who,{...add(current),ownerId:other.userId}),error(400));await assert.rejects(service.mutate(who,add(current),AbortSignal.abort()));
 await f.db.query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[who.userId]);await assert.rejects(service.read(who),error(401));
});
test('late auth reset rolls back a new plan and encrypted data; immutable rows only disappear with the owner',async()=>{
 const who=await born(),cmd=add(await service.read(who)),original=f.db.withBoundedTransaction.bind(f.db);
 f.db.withBoundedTransaction=async(fn,options)=>original(c=>fn(new Proxy(c,{get(target,key){if(key==='query')return async(sql:any,...args:any[])=>{const result=await(target.query as any)(sql,...args);if(typeof sql==='string'&&sql.startsWith('INSERT INTO platform_daily_plan_operations'))await target.query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[who.userId]);return result;};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}})),options);
 try{await assert.rejects(service.mutate(who,cmd),error(401));}finally{f.db.withBoundedTransaction=original;}
 assert.equal((await service.read(who)).plan,null);await service.mutate(who,cmd);
 for(const table of ['platform_daily_plans','platform_daily_plan_items','platform_daily_plan_operations'])await assert.rejects(f.db.query(`DELETE FROM ${table} WHERE user_id=$1`,[who.userId]));
 await f.db.query('DELETE FROM platform_users WHERE id=$1',[who.userId]);for(const table of ['platform_daily_plans','platform_daily_plan_items','platform_daily_plan_operations'])assert.equal((await f.db.query(`SELECT * FROM ${table} WHERE user_id=$1`,[who.userId])).rowCount,0);
});
test('owner export includes current tasks and over 100 history revisions without credentials or foreign task text',async()=>{
 const who=await born(),other=await born();await service.mutate(other,{...add(await service.read(other)),title:'FOREIGN_PRIVATE_TASK'});let view=await service.read(who);
 for(let i=0;i<35;i++){view=(await service.mutate(who,add(view,1))).view;view=(await service.mutate(who,command(view,{action:'accept'}))).view;view=(await service.mutate(who,command(view,{action:'drop',itemId:view.plan!.items.at(-1)!.id}))).view;}
 const password='Fictional-private-plan-export-password';await f.db.query('UPDATE platform_users SET password_hash=$2 WHERE id=$1',[who.userId,await hashPassword(password)]);await f.db.query('DELETE FROM platform_terms_consents WHERE user_id=$1',[who.userId]);const proof=(await new AccountReauthentication(f.db).verify(who,{purpose:'account_export',password})).token;const result=await new AccountCoreExport(f.db,f.config).capture(who,proof);
 assert.equal(result.sections.dailyPlans.length,1);assert.equal(result.sections.dailyPlanHistory.length,105);assert.equal(result.complete,false);for(const table of ['platform_daily_plans','platform_daily_plan_items','platform_daily_plan_operations'])assert(result.includedTables.includes(table));
 const json=JSON.stringify(result);for(const secret of ['FOREIGN_PRIVATE_TASK',other.userId,who.tokenHash,password,proof,'acceptedAuthVersion','commandDigest','record_ciphertext'])assert(!json.includes(secret));assert(json.includes('PRIVATE_FICTIONAL_OWN_TASK'));
});

test('failure during the second half of a move rolls back both days, and malformed saved projections fail closed',async()=>{
 const who=await born();let v=(await service.mutate(who,add(await service.read(who)))).view;v=(await service.mutate(who,command(v,{action:'accept'}))).view;const move=command(v,{action:'move',itemId:v.plan!.items[0].id}),original=f.db.withBoundedTransaction.bind(f.db);
 let inserts=0;f.db.withBoundedTransaction=async(fn,options)=>original(c=>fn(new Proxy(c,{get(target,key){if(key==='query')return async(sql:any,...args:any[])=>{if(typeof sql==='string'&&sql.startsWith('INSERT INTO platform_daily_plan_operations')&&++inserts===2)throw new ApiError(503,'FICTIONAL_WRITE_FAILURE','Fictional failure');return(target.query as any)(sql,...args);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}})),options);
 try{await assert.rejects(service.mutate(who,move),error(503));}finally{f.db.withBoundedTransaction=original;}assert.deepEqual(await service.read(who),v);assert.equal((await f.db.query('SELECT * FROM platform_daily_plans WHERE user_id=$1',[who.userId])).rowCount,1);assert.equal((await f.db.query('SELECT * FROM platform_daily_plan_items WHERE user_id=$1',[who.userId])).rowCount,1);await assert.rejects(service.observe(who,move.operationId),error(404));
 for(const mode of ['ciphertext','owner','items']){f.db.withBoundedTransaction=async(fn,options)=>original(c=>fn(new Proxy(c,{get(target,key){if(key==='query')return async(sql:any,...args:any[])=>{const result=await(target.query as any)(sql,...args);if(typeof sql==='string'&&sql.startsWith('SELECT * FROM platform_daily_plan_operations'))for(const row of result.rows){if(mode==='ciphertext'){row.record_ciphertext=Buffer.from(row.record_ciphertext);row.record_ciphertext[12]^=1;}if(mode==='owner')row.user_id=randomUUID();}if(mode==='items'&&typeof sql==='string'&&sql.startsWith('SELECT id,candidate_id FROM platform_daily_plan_items'))return{...result,rows:[]};return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}})),options);try{await assert.rejects(service.read(who),error(503));}finally{f.db.withBoundedTransaction=original;}}
});
