import { readFile } from 'node:fs/promises';
import { before,after,test } from 'node:test';import assert from 'node:assert/strict';import { randomUUID } from 'node:crypto';
import { ManualJobs } from '../src/manual-jobs.ts';import { ApiError } from '../src/errors.ts';import { FICTIONAL_LEGAL } from './fixtures/student-entry.ts';import { createCompanionNameSafetyFixture } from './fixtures/companion-name-safety.ts';
let f:Awaited<ReturnType<typeof createCompanionNameSafetyFixture>>,jobs:ManualJobs;
before(async()=>{f=await createCompanionNameSafetyFixture();jobs=new ManualJobs(f.db,f.config,FICTIONAL_LEGAL);});after(async()=>{await f?.close();});
const command=(patch:Record<string,unknown>={})=>({operationId:randomUUID(),expectedRevision:0,employer:'Fictional Company',title:'Fictional Analyst',canonicalUrl:'https://example.invalid/jobs/1?utm_source=fictional',roleFamily:'da',location:'Fictional City',deadlineAt:null,deadlineTimeZone:null,privateNote:'Fictional private note',jobText:'Fictional analytics role. We will not sponsor candidates.',...patch});const error=(status:number)=>(e:unknown)=>e instanceof ApiError&&e.status===status;
test('actual saved JD retains original text, encrypted fields, exact evidence and server time; forgetting prevents replay resurrection',async()=>{
 const who=await f.actor(),body=command(),saved=await jobs.mutate(who,'create',null,body),job=saved.job!;assert.equal(job.source,'manual');assert.equal(job.state,'unknown');assert.equal(job.sponsorship,'explicit_no');assert.equal(job.checkedAt,job.observedAt);assert.equal(job.jobText,body.jobText);assert.equal(job.sponsorshipEvidence[0].text,'We will not sponsor candidates.');
 const raw=(await f.db.query('SELECT * FROM platform_career_job_observations WHERE id=$1',[job.id])).rows[0];for(const text of [body.employer,body.privateNote,body.jobText,body.canonicalUrl])assert(!raw.record_ciphertext.includes(Buffer.from(text)));
 const list=await jobs.list(who);assert.equal(list.jobs.length,1);assert(!('jobText' in list.jobs[0]));assert(!('privateNote' in list.jobs[0]));assert.equal(list.nextAfter,null);
 assert.equal((await jobs.mutate(who,'create',null,body)).operation.replayed,true);await assert.rejects(jobs.mutate(who,'create',null,{...body,jobText:'Fictional reused operation.'}),error(409));
 const deletion={operationId:randomUUID(),expectedRevision:1};assert.equal((await jobs.mutate(who,'delete',job.id,deletion)).job,null);assert.equal((await jobs.mutate(who,'delete',job.id,deletion)).operation.replayed,true);assert.equal((await jobs.mutate(who,'create',null,body)).job,null);assert.equal((await jobs.list(who)).jobs.length,0);await assert.rejects(jobs.get(who,job.id),error(404));
 for(const row of (await f.db.query('SELECT * FROM platform_career_job_observation_operations WHERE user_id=$1',[who.userId])).rows){const receipt=f.crypto.openUtf8(row.receipt_ciphertext,{table:'platform_career_job_observation_operations',column:'receipt_ciphertext',rowId:row.operation_id,ownerId:who.userId,revision:row.applied_revision});assert(!receipt.includes('Fictional'));}
});
test('duplicates require an explicit new owner action; canonical links, normalized title pairs and concurrency cannot bypass it',async()=>{
 const who=await f.actor(),first=await jobs.mutate(who,'create',null,command());await assert.rejects(jobs.mutate(who,'create',null,command({title:'Fictional Other',canonicalUrl:'https://example.invalid/jobs/1?utm_medium=synthetic'})),error(409));
 const duplicate=command({canonicalUrl:'https://example.invalid/jobs/2',employer:'Ｆｉｃｔｉｏｎａｌ Company',title:'fictional  analyst'});const actual=await jobs.duplicates(who,duplicate);assert.equal(actual.jobs[0].id,first.job!.id);await assert.rejects(jobs.mutate(who,'create',null,duplicate),error(409));const second=await jobs.mutate(who,'create',null,{...duplicate,allowDuplicate:true});assert.notEqual(second.job!.id,first.job!.id);
 const other=await f.actor(),a=command(),b=command(),results=await Promise.allSettled([a,b].map(c=>jobs.mutate(other,'create',null,c)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await jobs.list(other)).jobs.length,1);
});
test('owner-bound pagination never includes other users or silently drops older jobs',async()=>{
 const who=await f.actor(),other=await f.actor();for(let i=0;i<53;i++)await jobs.mutate(who,'create',null,command({employer:'Fictional Company '+i,canonicalUrl:'https://example.invalid/jobs/'+i}));await jobs.mutate(other,'create',null,command());
 const first=await jobs.list(who);assert.equal(first.jobs.length,50);assert(first.nextAfter);const second=await jobs.list(who,{after:first.nextAfter});assert.equal(second.jobs.length,3);assert.equal(second.nextAfter,null);assert.equal(new Set([...first.jobs,...second.jobs].map(j=>j.id)).size,53);assert.equal((await jobs.list(other)).jobs.length,1);await assert.rejects(jobs.list(other,{after:first.nextAfter}),error(404));
});
test('foreign, staff, revoked and withdrawn-admission cases respect private read/delete versus new saving',async()=>{
 const who=await f.actor(),other=await f.actor(),staff=await f.actor(true),saved=await jobs.mutate(who,'create',null,command()),id=saved.job!.id;
 await assert.rejects(jobs.get(other,id),error(404));await assert.rejects(jobs.mutate(other,'delete',id,{operationId:randomUUID(),expectedRevision:1}),error(404));assert.equal((await jobs.duplicates(other,command())).jobs.length,0);await assert.rejects(jobs.get(staff,id),error(403));
 await f.db.query('DELETE FROM platform_terms_consents WHERE user_id=$1',[who.userId]);await f.db.query('UPDATE platform_users SET email_verified_at=NULL WHERE id=$1',[who.userId]);assert.equal((await jobs.get(who,id)).id,id);await assert.rejects(jobs.mutate(who,'create',null,command({allowDuplicate:true})),error(403));await jobs.mutate(who,'delete',id,{operationId:randomUUID(),expectedRevision:1});
 const revoked=await f.actor(),record=await jobs.mutate(revoked,'create',null,command());await f.db.query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[revoked.userId]);await assert.rejects(jobs.get(revoked,record.job!.id),error(401));
});
test('current encrypted record authentication refuses forged open state, tampered ciphertext and mutable operation receipts',async()=>{
 const who=await f.actor(),saved=await jobs.mutate(who,'create',null,command()),id=saved.job!.id;await assert.rejects(f.db.query("UPDATE platform_career_job_observations SET state='observed_open' WHERE id=$1",[id]));
 await f.db.query('UPDATE platform_career_job_observations SET record_ciphertext=$2 WHERE id=$1',[id,Buffer.alloc(40)]);await assert.rejects(jobs.get(who,id),error(503));await assert.rejects(f.db.query('DELETE FROM platform_career_job_observation_operations WHERE user_id=$1',[who.userId]));
});
test('an actual late session reset rolls back the record and its immutable receipt together',async()=>{
 const who=await f.actor(),original=f.db.withBoundedTransaction.bind(f.db);f.db.withBoundedTransaction=async(run,options)=>original(async client=>{const query=client.query.bind(client);let reset=false;const guarded=new Proxy(client,{get(target,key){if(key==='query')return async(...args:any[])=>{const result=await (query as any)(...args);if(!reset&&typeof args[0]==='string'&&args[0].startsWith('INSERT INTO platform_career_job_observations')){reset=true;await query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[who.userId]);}return result;};return Reflect.get(target,key);}});return run(guarded);},options);
 try{await assert.rejects(jobs.mutate(who,'create',null,command()),error(401));}finally{f.db.withBoundedTransaction=original;}for(const table of ['platform_career_job_observations','platform_career_job_observation_operations'])assert.equal((await f.db.query('SELECT user_id FROM '+table+' WHERE user_id=$1',[who.userId])).rowCount,0);
});
test('actual account deletion cascades saved text and receipts, and migrations are idempotent',async()=>{
 const who=await f.actor();await jobs.mutate(who,'create',null,command());await f.db.query('DELETE FROM platform_users WHERE id=$1',[who.userId]);for(const table of ['platform_career_job_observations','platform_career_job_observation_operations'])assert.equal((await f.db.query('SELECT user_id FROM '+table+' WHERE user_id=$1',[who.userId])).rowCount,0);await f.db.migrate();await f.db.query(await readFile(new URL('../migrations/056_manual_job_observations.sql',import.meta.url),'utf8'));
});

test('restoring a previously authentic removed snapshot cannot undo the immutable forget operation',async()=>{
 const who=await f.actor(),first=await jobs.mutate(who,'create',null,command()),id=first.job!.id,row=(await f.db.query('SELECT * FROM platform_career_job_observations WHERE id=$1',[id])).rows[0];await jobs.mutate(who,'delete',id,{operationId:randomUUID(),expectedRevision:1});
 await f.db.query('INSERT INTO platform_career_job_observations(id,user_id,source,state,revision,last_operation_id,observed_at,checked_at,created_at,updated_at,record_ciphertext) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$7,$7,$9)',[row.id,row.user_id,row.source,row.state,row.revision,row.last_operation_id,row.observed_at,row.checked_at,row.record_ciphertext]);await assert.rejects(jobs.get(who,id),error(503));await assert.rejects(jobs.list(who),error(503));
});
