import { before,after,test } from 'node:test';import assert from 'node:assert/strict';import { randomUUID,createHash } from 'node:crypto';import { mkdtemp,rm,readFile } from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import { ResumeOriginalReview } from '../src/resume-original-review.ts';import { LocalBlobStorage } from '../src/storage.ts';import { ApiError } from '../src/errors.ts';import { FICTIONAL_LEGAL } from './fixtures/student-entry.ts';import { createCompanionNameSafetyFixture } from './fixtures/companion-name-safety.ts';import { fictionalResumePdf } from './fixtures/resume-pdf.ts';
let f:Awaited<ReturnType<typeof createCompanionNameSafetyFixture>>,directory:string,storage:LocalBlobStorage,resumes:ResumeOriginalReview;
before(async()=>{f=await createCompanionNameSafetyFixture();directory=await mkdtemp(path.join(os.tmpdir(),'fictional-resume-upload-'));storage=new LocalBlobStorage(directory);resumes=new ResumeOriginalReview(f.db,{...f.config,productEventsEnabled:true},FICTIONAL_LEGAL,storage);});after(async()=>{await f?.close();await rm(directory,{recursive:true,force:true});});
const sha=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex'),action=(v:any)=>({operationId:randomUUID(),expectedRevision:v.item.revision,payloadDigest:v.item.payloadDigest}),error=(n:number)=>(e:unknown)=>e instanceof ApiError&&e.status===n;
async function store(who:{userId:string},bytes:Buffer=fictionalResumePdf(),mime='application/pdf'){const id=randomUUID(),key=randomUUID(),name=mime==='application/pdf'?'Fictional CV.pdf':'Fictional CV.txt';await storage.put(key,bytes);await f.db.query('INSERT INTO platform_uploads(id,user_id,filename,mime,byte_size,storage_key) VALUES($1,$2,$3,$4,$5,$6)',[id,who.userId,name,mime,bytes.length,key]);return {id,key,bytes,command:{operationId:randomUUID(),expectedRevision:0,track:'da',label:'Fictional uploaded original',uploadId:id,sha256:sha(bytes)}};}
test('actual owned PDF capture, original history, edits and Web confirmation preserve authenticated file provenance without model facts',async()=>{const who=await f.actor(),file=await store(who),saved=await resumes.createFromUpload(who,file.command),v=saved.view!;assert.equal(v.item.source,'upload');assert.equal(v.item.uploadId,file.id);assert.equal(v.item.uploadSource!.sha256,sha(file.bytes));assert.equal(v.item.uploadSource!.textSha256,sha(v.payload.text));assert.equal(v.item.uploadSource!.parser,'pdftotext');assert(v.payload.text.includes('Fictional CV'));assert.equal(v.payload.source_refs[1]!.id,file.id);assert.deepEqual(v.payload.claims,[]);assert.equal(v.item.draftedBy,null);
 const changed=(await resumes.mutate(who,'edit',v.item.id,{...action(v),label:'Fictional checked original',text:'Fictional corrected individual contribution.'},'web')).view!;assert.equal(changed.item.source,'upload');assert.equal(changed.item.uploadSource!.textSha256,sha(v.payload.text));assert.equal((await resumes.revision(who,v.item.id,1)).payload.text,v.payload.text);
 const approved=(await resumes.mutate(who,'approve',v.item.id,action(changed),'web')).view!;assert.equal(approved.item.resumeStatus,'active');const repeated=await resumes.createFromUpload(who,file.command);assert.equal(repeated.operation.replayed,true);assert.equal(repeated.view!.item.status,'approved');assert.equal(repeated.view!.item.revision,2);
 await resumes.mutate(who,'delete',v.item.id,action(approved),'web');await storage.delete(file.key);await f.db.query('DELETE FROM platform_uploads WHERE id=$1',[file.id]);assert.equal((await resumes.createFromUpload(who,file.command)).view,null);assert.deepEqual((await f.db.query('SELECT event,props,channel FROM platform_product_events WHERE user_id=$1',[who.userId])).rows,[{event:'resume_version_created',props:{source:'upload'},channel:'web'}]);await f.db.query(await readFile(new URL('../migrations/060_resume_upload_original.sql',import.meta.url),'utf8'));});
test('UTF-8 full text and current owner selections without a client digest still receive a real storage fingerprint and exact body',async()=>{const who=await f.actor(),text='虚构课程项目\nFictional owner action. 🚀',file=await store(who,Buffer.from(text),'text/plain'),{sha256:_,...command}=file.command;const v=(await resumes.createFromUpload(who,command)).view!;assert.equal(v.payload.text,text);assert.equal(v.item.uploadSource!.sha256,sha(file.bytes));assert.equal(v.item.uploadSource!.parser,'utf8');assert.equal(v.item.uploadSource!.engineVersion,process.versions.node);});
test('foreign, staff, wrong source bytes, unsupported MIME and fabricated extraction fields are rejected before an original is created',async()=>{const who=await f.actor(),other=await f.actor(),staff=await f.actor(true),file=await store(who);await assert.rejects(resumes.createFromUpload(other,file.command),error(404));await assert.rejects(resumes.createFromUpload(staff,file.command),error(403));await assert.rejects(resumes.createFromUpload(who,{...file.command,sha256:'a'.repeat(64)}),error(409));for(const patch of [{text:'invented'},{parser:'pdftotext'},{source:'upload'},{uploadSource:{}},{draftedBy:'guide'}])await assert.rejects(resumes.createFromUpload(who,{...file.command,...patch}),error(400));assert.equal((await resumes.list(who)).items.length,0);const binary=await store(who,Buffer.from('Fictional'),'application/json');await assert.rejects(resumes.createFromUpload(who,binary.command),error(415));});
test('incomplete, disguised binary, invalid UTF-8 and overlong files cannot create truncated originals',async()=>{const who=await f.actor();for(const [bytes,mime] of [[fictionalResumePdf(['Fictional page.','']),'application/pdf'],[Buffer.from('%PDF-disguised'),'text/plain'],[Buffer.from([0xff]),'text/plain'],[Buffer.from('x'.repeat(50001)),'text/plain']] as const){const file=await store(who,bytes,mime);await assert.rejects(resumes.createFromUpload(who,file.command),e=>e instanceof ApiError);}assert.equal((await resumes.list(who)).items.length,0);});
test('actual current metadata, legal admission and fixed session are checked again after file I/O before preserving an original or replacing a draft',async()=>{const who=await f.actor(),file=await store(who),original=storage.stat.bind(storage);let reads=0;storage.stat=async(...args)=>{const stat=await original(...args);if(++reads===2)await f.db.query('UPDATE platform_users SET auth_version=auth_version+1 WHERE id=$1',[who.userId]);return stat;};try{await assert.rejects(resumes.createFromUpload(who,file.command),error(401));}finally{storage.stat=original;}assert.equal((await f.db.query('SELECT id FROM platform_pending_items WHERE user_id=$1',[who.userId])).rowCount,0);
 const other=await f.actor(),changed=await store(other),base=storage.stat.bind(storage);reads=0;storage.stat=async(...args)=>{const stat=await base(...args);if(++reads===2)await f.db.query("UPDATE platform_uploads SET filename='Fictional changed metadata.pdf' WHERE id=$1",[changed.id]);return stat;};try{await assert.rejects(resumes.createFromUpload(other,changed.command),error(409));}finally{storage.stat=base;}assert.equal((await resumes.list(other)).items.length,0);await f.db.query('DELETE FROM platform_terms_consents WHERE user_id=$1',[other.userId]);await assert.rejects(resumes.createFromUpload(other,changed.command),error(403));});
test('real owned upload pagination uses database cursor precision, excludes foreign cursors and never returns keys or original bytes',async()=>{const who=await f.actor(),other=await f.actor();for(let i=0;i<52;i++)await store(who,Buffer.from('Fictional private body'),'text/plain');const first=await resumes.listUploads(who);assert.equal(first.files.length,50);const second=await resumes.listUploads(who,{after:first.nextAfter});assert.equal(second.files.length,2);assert.equal(second.nextAfter,null);assert(!JSON.stringify(first).includes('private body'));assert(!JSON.stringify(first).includes('storageKey'));await assert.rejects(resumes.listUploads(other,{after:first.nextAfter}),error(404));});

test('the file I/O boundary admits at most two real reads and releases both slots after completion',async()=>{
 const firstOwner=await f.actor(),secondOwner=await f.actor(),thirdOwner=await f.actor(),a=await store(firstOwner,Buffer.from('Fictional first.'),'text/plain'),b=await store(secondOwner,Buffer.from('Fictional second.'),'text/plain'),c=await store(thirdOwner,Buffer.from('Fictional third.'),'text/plain');
 const original=storage.stat.bind(storage);let release!:()=>void,ready!:()=>void,entered=0;const gate=new Promise<void>(r=>{release=r;}),both=new Promise<void>(r=>{ready=r;});storage.stat=async(...args)=>{const stat=await original(...args);if(++entered<=2){if(entered===2)ready();await gate;}return stat;};
 const p1=resumes.createFromUpload(firstOwner,a.command),p2=resumes.createFromUpload(secondOwner,b.command);
 try{await both;await assert.rejects(resumes.createFromUpload(thirdOwner,c.command),e=>e instanceof ApiError&&e.status===503&&e.code==='RESUME_TEXT_BUSY');release();assert.equal((await p1).view!.item.status,'pending');assert.equal((await p2).view!.item.status,'pending');assert.equal((await resumes.createFromUpload(thirdOwner,c.command)).view!.item.status,'pending');}finally{release();await Promise.allSettled([p1,p2]);storage.stat=original;}
});
