import { createHash,randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { careerRecordId,careerRecordObject,parseCareerLibraryCommand,parseCareerProject,parseCareerStory,careerLibrarySummary,type CareerLibraryKind,type CareerLibraryAction,type CareerLibraryRecord,type CareerProject,type CareerStory,type CareerStoryEvidenceAvailability } from '@companion/platform-contracts';
import { careerProgress } from '@companion/career-core';
import { authorizeFixedSession,type FixedSessionContext } from './auth.ts';
import type { Database } from './database.ts';
import type { PlatformConfig } from './config.ts';
import type { LegalBundle } from './legal-documents.ts';
import { OnboardingStorage } from './onboarding-storage.ts';
import { ApiError } from './errors.ts';
const tables={project:'platform_career_evidence',story:'platform_career_stories'} as const;
const unavailable=()=>new ApiError(503,'CAREER_LIBRARY_STORAGE_UNAVAILABLE','The saved experience could not be confirmed.');
const bad=()=>new ApiError(400,'CAREER_LIBRARY_INPUT_INVALID','Use explicit experience fields.');
const missing=()=>new ApiError(404,'NOT_FOUND','The saved experience was not found.');
const changed=()=>new ApiError(409,'CAREER_LIBRARY_REVISION_CHANGED','Read the current experience before changing it.');
const canonical=(v:unknown)=>JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
interface Receipt {schemaVersion:1;ownerId:string;operationId:string;recordKind:CareerLibraryKind;recordId:string;action:CareerLibraryAction;commandDigest:string;appliedRevision:number;acceptedAuthVersion:string;createdAt:string;}
/** Owner facts and story decisions only. This does not produce expert proposals,
 * source safety classification, model use, mentor review or execution permission. */
export class CareerStories {
 private readonly storage:OnboardingStorage;
 constructor(private readonly db:Database,config:Pick<PlatformConfig,'dataCrypto'|'requireVerifiedEmail'>,legal:LegalBundle|null){this.storage=new OnboardingStorage(config,legal);}
 private kind(value:CareerLibraryKind){if(value!=='project'&&value!=='story')throw bad();return value;}
 private fixed(value:FixedSessionContext){try{const v=careerRecordObject(value,['userId','tokenHash']);if(typeof v.tokenHash!=='string'||!/^[0-9a-f]{64}$/.test(v.tokenHash))throw bad();return Object.freeze({userId:careerRecordId(v.userId),tokenHash:v.tokenHash});}catch{throw new ApiError(401,'AUTH_REQUIRED','Sign in to continue.');}}
 private async authorize(client:PoolClient,context:FixedSessionContext,signal?:AbortSignal){await authorizeFixedSession(client,context,signal);const row=(await client.query('SELECT account_kind,auth_version FROM platform_users WHERE id=$1 FOR NO KEY UPDATE',[context.userId])).rows[0];if(row?.account_kind!=='student')throw new ApiError(403,'STUDENT_ACCOUNT_REQUIRED','Use a student account.');if(!this.storage.crypto)throw unavailable();signal?.throwIfAborted();return row;}
 private async receipt(client:PoolClient,context:FixedSessionContext,row:any):Promise<Receipt>{try{
  const raw=this.storage.crypto!.openUtf8(row.receipt_ciphertext,{table:'platform_career_library_operations',column:'receipt_ciphertext',rowId:row.operation_id,ownerId:context.userId,revision:row.applied_revision});
  const r=careerRecordObject(JSON.parse(raw),['schemaVersion','ownerId','operationId','recordKind','recordId','action','commandDigest','appliedRevision','acceptedAuthVersion','createdAt']);
  if(canonical(r)!==raw||r.schemaVersion!==1||r.ownerId!==context.userId||r.operationId!==row.operation_id||r.recordKind!==row.record_kind||r.recordId!==row.record_id||r.action!==row.action||r.appliedRevision!==row.applied_revision||r.createdAt!==row.created_at.toISOString()||typeof r.commandDigest!=='string'||!/^[0-9a-f]{64}$/.test(r.commandDigest)||typeof r.acceptedAuthVersion!=='string'||!/^(0|[1-9][0-9]*)$/.test(r.acceptedAuthVersion))throw unavailable();return r as unknown as Receipt;
 }catch{throw unavailable();}}
 private async latest(client:PoolClient,context:FixedSessionContext,kind:CareerLibraryKind,id:string){const row=(await client.query('SELECT * FROM platform_career_library_operations WHERE user_id=$1 AND record_kind=$2 AND record_id=$3 ORDER BY applied_revision DESC LIMIT 1 FOR SHARE',[context.userId,kind,id])).rows[0];if(!row)throw unavailable();return this.receipt(client,context,row);}
 private async record(client:PoolClient,context:FixedSessionContext,kind:CareerLibraryKind,row:any):Promise<Readonly<CareerLibraryRecord>>{try{
  const raw=this.storage.crypto!.openUtf8(row.record_ciphertext,{table:tables[kind],column:'record_ciphertext',rowId:row.id,ownerId:context.userId,revision:row.revision}),record=kind==='project'?parseCareerProject(JSON.parse(raw)):parseCareerStory(JSON.parse(raw)),latest=await this.latest(client,context,kind,row.id);
  if(canonical(record)!==raw||record.id!==row.id||record.ownerId!==context.userId||record.revision!==row.revision||record.createdAt!==row.created_at.toISOString()||record.updatedAt!==row.updated_at.toISOString()||record.sensitivity!==row.sensitivity||record.lastOperationId!==row.last_operation_id||row.record_kind!==kind||latest.action==='delete'||latest.appliedRevision!==record.revision||latest.operationId!==record.lastOperationId||latest.createdAt!==record.updatedAt)throw unavailable();
  if(kind==='project'){const p=record as CareerProject;if(p.kind!==row.kind||p.state!==row.state||p.verification!==row.verification||row.mentor_review!==null)throw unavailable();if(p.state==='active'){if(row.withdrawn_at!==null)throw unavailable();}else{const r=(await client.query("SELECT * FROM platform_career_library_operations WHERE user_id=$1 AND record_kind='project' AND record_id=$2 AND action='withdraw' ORDER BY applied_revision DESC LIMIT 1 FOR SHARE",[context.userId,p.id])).rows[0];if(!r)throw unavailable();const withdrawal=await this.receipt(client,context,r);if(withdrawal.appliedRevision>p.revision||withdrawal.createdAt!==row.withdrawn_at?.toISOString())throw unavailable();}}else if((record as CareerStory).status!==row.status)throw unavailable();
  if(record.confirmedRevision!==null){const row=(await client.query('SELECT * FROM platform_career_library_operations WHERE user_id=$1 AND record_kind=$2 AND record_id=$3 AND applied_revision=$4 FOR SHARE',[context.userId,kind,record.id,record.confirmedRevision])).rows[0];if(!row)throw unavailable();const confirmation=await this.receipt(client,context,row);if(confirmation.action!=='confirm'||confirmation.createdAt!==record.confirmedAt)throw unavailable();}
  return record;
 }catch{throw unavailable();}}
 private async row(client:PoolClient,context:FixedSessionContext,kind:CareerLibraryKind,id:string){return (await client.query('SELECT * FROM '+tables[kind]+' WHERE user_id=$1 AND id=$2 FOR UPDATE',[context.userId,id])).rows[0];}
 private async availability(client:PoolClient,context:FixedSessionContext,story:Readonly<CareerStory>,signal?:AbortSignal):Promise<CareerStoryEvidenceAvailability>{
  let state:CareerStoryEvidenceAvailability='current';
  for(const ref of story.projects){signal?.throwIfAborted();const row=await this.row(client,context,'project',ref.id);if(!row)return 'missing';const p=await this.record(client,context,'project',row) as CareerProject;if(p.state==='withdrawn')return 'withdrawn';if(p.revision!==ref.revision)state='stale';else if(p.verification!=='user_confirmed'&&state==='current')state='unconfirmed';}
  return state;
 }
 private async linked(client:PoolClient,context:FixedSessionContext,story:Readonly<CareerStory>,signal?:AbortSignal){const rank={normal:0,sensitive:1,restricted:2};
  for(const ref of story.projects){signal?.throwIfAborted();const row=await this.row(client,context,'project',ref.id);if(!row)throw missing();const p=await this.record(client,context,'project',row) as CareerProject;
   if(p.revision!==ref.revision||p.state!=='active')throw new ApiError(409,'CAREER_STORY_EVIDENCE_CHANGED','Read the current project facts before linking them.');
   if(p.experienceKind!==story.experienceKind)throw new ApiError(400,'CAREER_STORY_SOURCE_KIND','Keep the actual experience label when linking project facts.');
   if(rank[story.sensitivity]<rank[p.sensitivity])throw new ApiError(400,'CAREER_STORY_SENSITIVITY','The story privacy level must also protect its linked facts.');
  }
 }
 async get(value:FixedSessionContext,inputKind:CareerLibraryKind,key:unknown,signal?:AbortSignal){const context=this.fixed(value),kind=this.kind(inputKind);let id:string;try{id=careerRecordId(key);}catch{throw bad();}
  return this.db.withBoundedTransaction(async client=>{await this.authorize(client,context,signal);const row=await this.row(client,context,kind,id);if(!row)throw missing();const record=await this.record(client,context,kind,row),evidenceAvailability=kind==='story'?await this.availability(client,context,record as CareerStory,signal):null;await authorizeFixedSession(client,context,signal);return Object.freeze({record,evidenceAvailability});});}
 async list(value:FixedSessionContext,inputKind:CareerLibraryKind,query:unknown={},signal?:AbortSignal){const context=this.fixed(value),kind=this.kind(inputKind);let after:string|null;try{const q=careerRecordObject(query,[],['after']);after=Object.hasOwn(q,'after')?careerRecordId(q.after):null;}catch{throw bad();}
  return this.db.withBoundedTransaction(async client=>{await this.authorize(client,context,signal);let cursor:any=null;if(after){cursor=await this.row(client,context,kind,after);if(!cursor)throw missing();await this.record(client,context,kind,cursor);}
   const rows=(await client.query('SELECT * FROM '+tables[kind]+' WHERE user_id=$1 AND ($2::timestamptz IS NULL OR (created_at,id)<($2::timestamptz,$3::uuid)) ORDER BY created_at DESC,id DESC LIMIT 51 FOR SHARE',[context.userId,cursor?.created_at??null,after])).rows,records=[];
   for(const row of rows.slice(0,50)){signal?.throwIfAborted();const record=await this.record(client,context,kind,row);records.push(Object.freeze({record:careerLibrarySummary(kind,record),evidenceAvailability:kind==='story'?await this.availability(client,context,record as CareerStory,signal):null}));}await authorizeFixedSession(client,context,signal);return Object.freeze({records:Object.freeze(records),nextAfter:rows.length>50?records.at(-1)!.record.id:null});
  });}
 async progress(value:FixedSessionContext,signal?:AbortSignal){const context=this.fixed(value);return this.db.withBoundedTransaction(async client=>{await this.authorize(client,context,signal);const rows=(await client.query('SELECT * FROM platform_career_evidence WHERE user_id=$1 ORDER BY created_at,id LIMIT 501 FOR SHARE',[context.userId])).rows;if(rows.length>500)throw unavailable();const evidence=[];for(const row of rows){signal?.throwIfAborted();evidence.push(await this.record(client,context,'project',row) as CareerProject);}const progress=careerProgress(context.userId,evidence);await authorizeFixedSession(client,context,signal);return Object.freeze({progress,coverage:Object.freeze(['project'])});});}
 async mutate(value:FixedSessionContext,inputKind:CareerLibraryKind,action:CareerLibraryAction,key:unknown,input:unknown,signal?:AbortSignal){const context=this.fixed(value),kind=this.kind(inputKind);let command:ReturnType<typeof parseCareerLibraryCommand>,requested:string|null;try{command=parseCareerLibraryCommand(kind,action,input);requested=action==='create'?null:careerRecordId(key);}catch{throw bad();}
  const digest=createHash('sha256').update(canonical({kind,action,recordId:requested,command})).digest('hex');
  return this.db.withBoundedTransaction(async client=>{const auth=await this.authorize(client,context,signal),prior=(await client.query('SELECT * FROM platform_career_library_operations WHERE user_id=$1 AND operation_id=$2 FOR SHARE',[context.userId,command.operationId])).rows[0];
   if(prior){const receipt=await this.receipt(client,context,prior);if(receipt.commandDigest!==digest||receipt.recordKind!==kind||receipt.action!==action||requested!==null&&receipt.recordId!==requested)throw new ApiError(409,'CAREER_LIBRARY_OPERATION_CONFLICT','The experience operation was already used.');
    const row=await this.row(client,context,kind,receipt.recordId);let record:Readonly<CareerLibraryRecord>|null=null;if(row)record=await this.record(client,context,kind,row);else if((await this.latest(client,context,kind,receipt.recordId)).action!=='delete')throw unavailable();const evidenceAvailability=kind==='story'&&record?await this.availability(client,context,record as CareerStory,signal):null;await authorizeFixedSession(client,context,signal);return Object.freeze({record,evidenceAvailability,operation:Object.freeze({id:receipt.operationId,recordId:receipt.recordId,recordKind:kind,appliedRevision:receipt.appliedRevision,replayed:true})});}
   const id=requested??randomUUID();let base:Readonly<CareerLibraryRecord>|null=null;if(action!=='create'){const row=await this.row(client,context,kind,id);if(!row)throw missing();base=await this.record(client,context,kind,row);if(base.revision!==command.expectedRevision)throw changed();}
   if(action!=='delete'&&action!=='withdraw')await this.storage.authorizeSession(client,context,signal);
   if(action==='create'&&(await client.query('SELECT count(*)::int count FROM '+tables[kind]+' WHERE user_id=$1',[context.userId])).rows[0].count>=500)throw new ApiError(409,'CAREER_LIBRARY_CAPACITY','Remove an old experience before saving another.');
   const revision=(base?.revision??0)+1;if(revision>2147483647)throw changed();const at=(await client.query('SELECT clock_timestamp() at')).rows[0].at.toISOString();let record:Readonly<CareerLibraryRecord>|null=null;
   if(action!=='delete'){const {operationId,expectedRevision,...fields}=command,confirmed=action==='confirm',keep=action==='withdraw';
    const common={...base,...fields,id,ownerId:context.userId,revision,createdAt:base?.createdAt??at,updatedAt:at,lastOperationId:operationId,source:'user_entered',confirmedAt:confirmed?at:keep?base!.confirmedAt:null,confirmedRevision:confirmed?revision:keep?base!.confirmedRevision:null};
    if(kind==='project'){record=parseCareerProject({...common,kind:'project',subjectId:id,referenceId:'career-project:'+id+':'+revision,state:action==='withdraw'?'withdrawn':action==='confirm'?'active':base?(base as CareerProject).state:'active',verification:confirmed?'user_confirmed':keep?(base as CareerProject).verification:'self_reported'});if(confirmed&&!(record as CareerProject).contribution.trim())throw new ApiError(400,'CAREER_PROJECT_CONTRIBUTION','Record what you personally did before confirming the facts.');}
    else {if(confirmed&&Object.values((base as CareerStory).english).some(v=>!v.trim()))throw new ApiError(400,'CAREER_STORY_INCOMPLETE','Complete the four English STAR sections before confirming this story.');record=parseCareerStory({...common,status:confirmed?'confirmed':'draft'});await this.linked(client,context,record,signal);if(confirmed&&(await this.availability(client,context,record,signal))!=='current')throw new ApiError(409,'CAREER_STORY_EVIDENCE_UNCONFIRMED','Confirm the linked project facts before confirming this story.');}
   }
   const receipt:Receipt={schemaVersion:1,ownerId:context.userId,operationId:command.operationId,recordKind:kind,recordId:id,action,commandDigest:digest,appliedRevision:revision,acceptedAuthVersion:String(auth.auth_version),createdAt:at};const sealed=this.storage.crypto!.sealUtf8(canonical(receipt),{table:'platform_career_library_operations',column:'receipt_ciphertext',rowId:receipt.operationId,ownerId:context.userId,revision});
   await client.query('INSERT INTO platform_career_library_operations(user_id,operation_id,record_kind,record_id,action,applied_revision,created_at,receipt_ciphertext) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[context.userId,command.operationId,kind,id,action,revision,at,sealed]);
   if(record){const cipher=this.storage.crypto!.sealUtf8(canonical(record),{table:tables[kind],column:'record_ciphertext',rowId:id,ownerId:context.userId,revision});
    if(kind==='project'){const p=record as CareerProject;let withdrawnAt:string|null=null;if(p.state==='withdrawn'){const wr=(await client.query("SELECT * FROM platform_career_library_operations WHERE user_id=$1 AND record_kind='project' AND record_id=$2 AND action='withdraw' ORDER BY applied_revision DESC LIMIT 1 FOR SHARE",[context.userId,id])).rows[0];if(!wr)throw unavailable();withdrawnAt=(await this.receipt(client,context,wr)).createdAt;}
     await client.query("INSERT INTO platform_career_evidence(id,user_id,kind,state,verification,sensitivity,revision,last_operation_id,record_ciphertext,created_at,updated_at,withdrawn_at) VALUES($1,$2,'project',$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET state=EXCLUDED.state,verification=EXCLUDED.verification,sensitivity=EXCLUDED.sensitivity,revision=EXCLUDED.revision,last_operation_id=EXCLUDED.last_operation_id,record_ciphertext=EXCLUDED.record_ciphertext,updated_at=EXCLUDED.updated_at,withdrawn_at=EXCLUDED.withdrawn_at",[id,context.userId,p.state,p.verification,p.sensitivity,revision,command.operationId,cipher,p.createdAt,at,withdrawnAt]);}
    else {const s=record as CareerStory;await client.query('INSERT INTO platform_career_stories(id,user_id,status,sensitivity,revision,last_operation_id,record_ciphertext,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,sensitivity=EXCLUDED.sensitivity,revision=EXCLUDED.revision,last_operation_id=EXCLUDED.last_operation_id,record_ciphertext=EXCLUDED.record_ciphertext,updated_at=EXCLUDED.updated_at',[id,context.userId,s.status,s.sensitivity,revision,command.operationId,cipher,s.createdAt,at]);}
   }else await client.query('DELETE FROM '+tables[kind]+' WHERE user_id=$1 AND id=$2',[context.userId,id]);
   const evidenceAvailability=kind==='story'&&record?await this.availability(client,context,record as CareerStory,signal):null;await authorizeFixedSession(client,context,signal);return Object.freeze({record,evidenceAvailability,operation:Object.freeze({id:command.operationId,recordId:id,recordKind:kind,appliedRevision:revision,replayed:false})});
  });}
}
