import {createHash,randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {careerRecordObject as object,careerRecordId as id,dailyDate,parseDailyPlan,parseDailyPlanCommand,parseDailyPlanView,type DailyPlan,type DailyPlanItem,type DailyPlanCommand,type DailyPlanResult} from '@companion/platform-contracts';
import {authorizeFixedSession,type FixedSessionContext} from './auth.ts';
import type {Database} from './database.ts';import type {PlatformConfig} from './config.ts';import type {LegalBundle} from './legal-documents.ts';
import {OnboardingStorage} from './onboarding-storage.ts';import {CompanionDailySettingsService} from './companion-daily-settings.ts';import {TodayRestService} from './today-rest.ts';import {ApiError} from './errors.ts';
const unavailable=()=>new ApiError(503,'DAILY_PLAN_UNAVAILABLE','The saved daily plan could not be confirmed.');
const bad=()=>new ApiError(400,'DAILY_PLAN_INPUT_INVALID','Use the current daily plan and an explicit action.');
const conflict=()=>new ApiError(409,'DAILY_PLAN_CHANGED','Read the current daily plan first.');
const canonical=(v:unknown)=>JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
function localDate(at:string,timeZone:string){const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(at));return dailyDate(['year','month','day'].map(k=>parts.find(p=>p.type===k)!.value).join('-'));}
const nextDate=(date:string,n=1)=>new Date(Date.parse(date+'T00:00:00.000Z')+n*86400000).toISOString().slice(0,10);
type PlanDraft=Omit<DailyPlan,'revision'|'lastOperationId'>&{revision:number;lastOperationId:string|null};
interface Saved {schemaVersion:1;ownerId:string;command:Readonly<DailyPlanCommand>;commandDigest:string;primaryPlanId:string;primaryRevision:number;acceptedAuthVersion:string;plan:Readonly<DailyPlan>;}
/** Explicit owner-created tasks only. Never marks an interview, job or skill complete. */
export class DailyPlans {
 private readonly storage:OnboardingStorage;private readonly daily:CompanionDailySettingsService;private readonly rest:TodayRestService;
 constructor(private readonly db:Database,config:Pick<PlatformConfig,'dataCrypto'|'requireVerifiedEmail'>,legal:LegalBundle|null){this.storage=new OnboardingStorage(config,legal);this.daily=new CompanionDailySettingsService(db,config,legal);this.rest=new TodayRestService(db,config,legal);}
 private fixed(value:FixedSessionContext){try{const v=object(value,['userId','tokenHash']);if(typeof v.tokenHash!=='string'||!/^[0-9a-f]{64}$/.test(v.tokenHash))throw bad();return Object.freeze({userId:id(v.userId),tokenHash:v.tokenHash});}catch{throw new ApiError(401,'AUTH_REQUIRED','Sign in to continue.');}}
 private async auth(c:PoolClient,s:FixedSessionContext,signal?:AbortSignal,lock=true){await authorizeFixedSession(c,s,signal);const u=(await c.query('SELECT account_kind,auth_version FROM platform_users WHERE id=$1'+(lock?' FOR NO KEY UPDATE':''),[s.userId])).rows[0];if(u?.account_kind!=='student')throw new ApiError(403,'STUDENT_ACCOUNT_REQUIRED','Use a student account.');if(!this.storage.crypto)throw unavailable();signal?.throwIfAborted();return u;}
 private async context(c:PoolClient,s:FixedSessionContext,signal?:AbortSignal){const settings=await this.daily.readOwnedInTransaction(c,s,signal);if(!settings.preferences)throw new ApiError(409,'DAILY_SETTINGS_REQUIRED','Choose your daily time zone first.');const rest=await this.rest.readOwnedInTransaction(c,s,signal);if(rest.companionId!==settings.companionId)throw unavailable();const at=(await c.query('SELECT clock_timestamp() at')).rows[0].at.toISOString();return{at,companionId:settings.companionId,timeZone:settings.preferences.timeZone,dailyMinutes:settings.preferences.dailyMinutes,localDate:localDate(at,settings.preferences.timeZone),paused:!!(rest.optedOutUntil&&rest.optedOutUntil>at||rest.pauseUntil&&rest.pauseUntil>at)};}
 private decode(s:FixedSessionContext,row:any):Saved{try{const raw=this.storage.crypto!.openUtf8(row.record_ciphertext,{table:'platform_daily_plan_operations',column:'record_ciphertext',rowId:row.operation_id,ownerId:s.userId,revision:row.revision});const v=object(JSON.parse(raw),['schemaVersion','ownerId','command','commandDigest','primaryPlanId','primaryRevision','acceptedAuthVersion','plan']),plan=parseDailyPlan(v.plan),command=parseDailyPlanCommand(v.command);
  if(canonical(v)!==raw||v.schemaVersion!==1||v.ownerId!==s.userId||row.user_id!==s.userId||plan.ownerId!==s.userId||plan.id!==row.plan_id||plan.revision!==row.revision||plan.lastOperationId!==row.operation_id||plan.updatedAt!==row.created_at.toISOString()||command.operationId!==row.operation_id||command.companionId!==plan.companionId||v.commandDigest!==hash({ownerId:s.userId,command})||typeof v.acceptedAuthVersion!=='string'||!/^(0|[1-9][0-9]*)$/.test(v.acceptedAuthVersion)||v.primaryRevision!==command.expectedRevision+1||command.planId!==null&&command.planId!==v.primaryPlanId)throw unavailable();id(v.primaryPlanId);
  if(plan.id===v.primaryPlanId&&(plan.revision!==v.primaryRevision||plan.localDate!==command.localDate)||plan.id!==v.primaryPlanId&&(command.action!=='move'||plan.localDate!==nextDate(command.localDate)))throw unavailable();return {...v,command,plan} as unknown as Saved;
 }catch{throw unavailable();}}
 private async load(c:PoolClient,s:FixedSessionContext,date:string):Promise<Readonly<DailyPlan>|null>{const head=(await c.query('SELECT *,local_date::text date_key FROM platform_daily_plans WHERE user_id=$1 AND local_date=$2 FOR SHARE',[s.userId,date])).rows[0];if(!head)return null;
  const row=(await c.query('SELECT * FROM platform_daily_plan_operations WHERE user_id=$1 AND plan_id=$2 ORDER BY revision DESC LIMIT 1 FOR SHARE',[s.userId,head.id])).rows[0];if(!row)throw unavailable();const p=this.decode(s,row).plan;
  if(p.id!==head.id||p.companionId!==head.companion_id||p.localDate!==head.date_key||p.createdAt!==head.created_at.toISOString())throw unavailable();
  const items=(await c.query('SELECT id,candidate_id FROM platform_daily_plan_items WHERE user_id=$1 AND plan_id=$2 ORDER BY id LIMIT 51 FOR SHARE',[s.userId,p.id])).rows;
  if(items.length!==p.items.length||items.some(row=>!p.items.some(i=>i.id===row.id&&i.candidateId===row.candidate_id)))throw unavailable();return p;
 }
 private async view(c:PoolClient,s:FixedSessionContext,ctx:Awaited<ReturnType<DailyPlans['context']>>){const plan=await this.load(c,s,ctx.localDate);return parseDailyPlanView({ownerId:s.userId,companionId:ctx.companionId,localDate:ctx.localDate,timeZone:ctx.timeZone,dailyMinutes:ctx.dailyMinutes,paused:ctx.paused,automaticStatus:'not_available',plan:ctx.paused?null:plan});}
 private async finish(c:PoolClient,s:FixedSessionContext,signal?:AbortSignal){await authorizeFixedSession(c,s,signal);signal?.throwIfAborted();}
 async read(value:FixedSessionContext,signal?:AbortSignal){const s=this.fixed(value);return this.db.withBoundedTransaction(async c=>{await this.auth(c,s,signal);const ctx=await this.context(c,s,signal),view=await this.view(c,s,ctx);await this.finish(c,s,signal);return view;});}
 private async prior(c:PoolClient,s:FixedSessionContext,operationId:string){const rows=(await c.query('SELECT * FROM platform_daily_plan_operations WHERE user_id=$1 AND operation_id=$2 ORDER BY plan_id LIMIT 3 FOR SHARE',[s.userId,operationId])).rows;if(!rows.length)return null;const all=rows.map(row=>this.decode(s,row)),primary=all.find(v=>v.plan.id===v.primaryPlanId);if(!primary||all.length!==(primary.command.action==='move'?2:1)||all.some(v=>v.primaryPlanId!==primary.primaryPlanId||v.primaryRevision!==primary.primaryRevision||v.commandDigest!==primary.commandDigest))throw unavailable();return primary;}
 private result(view:ReturnType<typeof parseDailyPlanView>,saved:Saved,replayed:boolean):Readonly<DailyPlanResult>{return Object.freeze({view,operation:Object.freeze({id:saved.command.operationId,action:saved.command.action,localDate:saved.command.localDate,planId:saved.primaryPlanId,appliedRevision:saved.primaryRevision,replayed})});}
 async observe(value:FixedSessionContext,key:unknown,signal?:AbortSignal){const s=this.fixed(value);let operationId:string;try{operationId=id(key);}catch{throw bad();}return this.db.withBoundedTransaction(async c=>{await this.auth(c,s,signal);const old=await this.prior(c,s,operationId);if(!old)throw new ApiError(404,'NOT_FOUND','The operation was not found.');const ctx=await this.context(c,s,signal);const result=this.result(await this.view(c,s,ctx),old,true);await this.finish(c,s,signal);return result;});}
 private async empty(c:PoolClient,s:FixedSessionContext,ctx:Awaited<ReturnType<DailyPlans['context']>>,date:string):Promise<PlanDraft>{const planId=randomUUID();await c.query('INSERT INTO platform_daily_plans(id,user_id,companion_id,local_date,created_at) VALUES($1,$2,$3,$4,$5)',[planId,s.userId,ctx.companionId,date,ctx.at]);return{id:planId,ownerId:s.userId,companionId:ctx.companionId,localDate:date,timeZone:ctx.timeZone,generatedBy:'rules',briefMessageId:null,acceptedAt:null,revision:0,createdAt:ctx.at,updatedAt:ctx.at,lastOperationId:null,items:[]};}
 private async marker(c:PoolClient,s:FixedSessionContext,planId:string,item:DailyPlanItem,at:string){await c.query('INSERT INTO platform_daily_plan_items(id,user_id,plan_id,candidate_id,created_at) VALUES($1,$2,$3,$4,$5)',[item.id,s.userId,planId,item.candidateId,at]);}
 private capacity(plan:PlanDraft,budget:number){if(plan.items.length>50)throw new ApiError(409,'DAILY_PLAN_CAPACITY','This daily plan is full.');if(plan.items.filter(i=>!['moved','dropped'].includes(i.state)).reduce((n,i)=>n+i.minutes,0)>budget)throw new ApiError(409,'DAILY_PLAN_BUDGET','The plan exceeds your chosen daily minutes.');}
 private async save(c:PoolClient,s:FixedSessionContext,draft:PlanDraft,command:DailyPlanCommand,primaryPlanId:string,authVersion:string,at:string):Promise<Saved>{const plan=parseDailyPlan({...draft,revision:draft.revision+1,lastOperationId:command.operationId,updatedAt:at});const record:Saved={schemaVersion:1,ownerId:s.userId,command,commandDigest:hash({ownerId:s.userId,command}),primaryPlanId,primaryRevision:command.expectedRevision+1,acceptedAuthVersion:authVersion,plan};const encrypted=this.storage.crypto!.sealUtf8(canonical(record),{table:'platform_daily_plan_operations',column:'record_ciphertext',rowId:command.operationId,ownerId:s.userId,revision:plan.revision});await c.query('INSERT INTO platform_daily_plan_operations(user_id,plan_id,revision,operation_id,created_at,record_ciphertext) VALUES($1,$2,$3,$4,$5,$6)',[s.userId,plan.id,plan.revision,command.operationId,at,encrypted]);return record;}
 async mutate(value:FixedSessionContext,input:unknown,signal?:AbortSignal){const s=this.fixed(value);let command:Readonly<DailyPlanCommand>;try{command=parseDailyPlanCommand(input);}catch{throw bad();}return this.db.withBoundedTransaction(async c=>{const user=await this.auth(c,s,signal),old=await this.prior(c,s,command.operationId),ctx=await this.context(c,s,signal);
  if(old){if(old.commandDigest!==hash({ownerId:s.userId,command}))throw new ApiError(409,'DAILY_PLAN_OPERATION_CONFLICT','The operation describes another choice.');const result=this.result(await this.view(c,s,ctx),old,true);await this.finish(c,s,signal);return result;}
  await this.storage.authorizeSession(c,s,signal);if(ctx.paused)throw new ApiError(409,'DAILY_PLAN_PAUSED','Your rest choice is still active.');if(command.localDate!==ctx.localDate||command.companionId!==ctx.companionId)throw conflict();
  const current=await this.load(c,s,ctx.localDate);if((current?.id??null)!==command.planId||(current?.revision??0)!==command.expectedRevision)throw conflict();
  const base:PlanDraft=current??await this.empty(c,s,ctx,ctx.localDate);let draft:PlanDraft={...base,items:[...base.items]};let tomorrow:PlanDraft|undefined;
  if(command.action==='add'){const item:DailyPlanItem={id:randomUUID(),candidateId:randomUUID(),title:command.title,minutes:command.minutes,rule:'user',state:'proposed',completedAt:null,completionSource:null,movedTo:null};draft={...draft,items:[...draft.items,item]};this.capacity(draft,ctx.dailyMinutes);await this.marker(c,s,draft.id,item,ctx.at);}
  else if(command.action==='accept'){if(!draft.items.some(i=>i.state==='proposed'))throw conflict();this.capacity(draft,ctx.dailyMinutes);draft={...draft,acceptedAt:ctx.at,items:draft.items.map(i=>i.state==='proposed'?{...i,state:'accepted'}:i)};}
  else {const selected=draft.items.find(i=>i.id===command.itemId);if(!selected)throw new ApiError(404,'NOT_FOUND','The daily item was not found.');if(selected.state!=='accepted')throw conflict();
   let updated:DailyPlanItem={...selected,state:command.action==='done'?'done':command.action==='drop'?'dropped':'moved',completedAt:command.action==='done'?ctx.at:null,completionSource:command.action==='done'?'self_reported':null};
   if(command.action==='move'){const date=nextDate(ctx.localDate);tomorrow=await this.load(c,s,date)??await this.empty(c,s,ctx,date);if(tomorrow.companionId!==ctx.companionId||tomorrow.items.some(i=>i.candidateId===selected.candidateId))throw conflict();const moved:DailyPlanItem={...selected,id:randomUUID(),state:'proposed',completedAt:null,completionSource:null,movedTo:null};tomorrow={...tomorrow,items:[...tomorrow.items,moved]};this.capacity(tomorrow,ctx.dailyMinutes);await this.marker(c,s,tomorrow.id,moved,ctx.at);updated={...updated,movedTo:{localDate:date,planId:tomorrow.id,itemId:moved.id}};}
   draft={...draft,items:draft.items.map(i=>i.id===selected.id?updated:i)};
  }
  const saved=await this.save(c,s,draft,command,draft.id,String(user.auth_version),ctx.at);if(tomorrow)await this.save(c,s,tomorrow,command,draft.id,String(user.auth_version),ctx.at);
  const result=this.result(await this.view(c,s,ctx),saved,false);await this.finish(c,s,signal);return result;
 });}
 /** Complete two preceding local dates for this plan store. No inferred achievements. */
 async readHistoryInTransaction(c:PoolClient,value:FixedSessionContext,at:string,timeZone:string,signal?:AbortSignal){const s=this.fixed(value);await this.auth(c,s,signal);await this.storage.authorizeSession(c,s,signal);const today=localDate(at,timeZone),dates=[nextDate(today,-1),nextDate(today,-2)] as const;const history=[];for(const date of dates){const plan=await this.load(c,s,date);if(plan)for(const item of plan.items)history.push(Object.freeze({candidateId:item.candidateId,ownerId:s.userId,localDate:date,outcome:item.state==='done'?'done' as const:['moved','dropped'].includes(item.state)?'dropped' as const:'unfinished' as const}));}await this.finish(c,s,signal);return Object.freeze({historyDates:Object.freeze(dates),history:Object.freeze(history),scope:'owner_created_tasks' as const});}
 async *exportInTransaction(c:PoolClient,value:FixedSessionContext,signal?:AbortSignal){const s=this.fixed(value);await this.auth(c,s,signal,false);let after:string|null=null;
  for(;;){const heads:any[]=(await c.query('SELECT id,local_date::text date_key FROM platform_daily_plans WHERE user_id=$1 AND ($2::uuid IS NULL OR id>$2) ORDER BY id LIMIT 100',[s.userId,after])).rows;for(const head of heads){signal?.throwIfAborted();const plan=await this.load(c,s,head.date_key);if(!plan||plan.id!==head.id)throw unavailable();yield{section:'dailyPlans' as const,record:plan};}if(heads.length<100)break;after=heads.at(-1).id;}
  let afterPlan:string|null=null,afterRevision=0;
  for(;;){const rows:any[]=(await c.query('SELECT * FROM platform_daily_plan_operations WHERE user_id=$1 AND ($2::uuid IS NULL OR (plan_id,revision)>($2::uuid,$3::integer)) ORDER BY plan_id,revision LIMIT 100',[s.userId,afterPlan,afterRevision])).rows;for(const row of rows){signal?.throwIfAborted();const saved=this.decode(s,row);yield{section:'dailyPlanHistory' as const,record:{plan:saved.plan,action:saved.command.action,operationId:saved.command.operationId}};}if(rows.length<100)break;afterPlan=rows.at(-1).plan_id;afterRevision=rows.at(-1).revision;}
  await this.finish(c,s,signal);
 }
}
