import { createProviderRuntime } from '@companion/ai-core';
import { Database } from './database.ts';
import { readConfig } from './config.ts';
import { createStorage } from './storage.ts';
import { createWorker, JobService, recoverInterrupted } from './jobs.ts';
import { startAccountEmailWorker } from './account-mail.ts';
const config=readConfig(),db=new Database(config.databaseUrl);
const jobs=new JobService(db,config,createProviderRuntime(),createStorage(config));
await db.query('SELECT 1');await recoverInterrupted(jobs);
const worker=createWorker(jobs);
const accountEmailWorker=startAccountEmailWorker(db,config.accountEmail);
worker.on('error',()=>{process.stderr.write('Worker connection interrupted; waiting for recovery.\n');});
const recovery=setInterval(()=>void recoverInterrupted(jobs).catch(()=>{}),15_000);recovery.unref();
process.stdout.write('Platform task worker started.\n');
for(const signal of ['SIGINT','SIGTERM'] as const)process.once(signal,()=>{clearInterval(recovery);void Promise.all([worker.close(),accountEmailWorker.close()]).then(()=>db.close()).then(()=>process.exit(0));});
