import { test } from 'node:test';import assert from 'node:assert/strict';import { randomUUID } from 'node:crypto';
import { parseCareerLibraryCommand,parseCareerProject,parseCareerStory } from '../src/career-stories.ts';
const star={situation:'Fictional course problem.',task:'Fictional research task.',action:'Fictional source comparison.',result:'Fictional feedback, no invented numerical result.'};
const story=()=>({operationId:randomUUID(),expectedRevision:0,title:'Fictional course story',experienceKind:'course_project',sensitivity:'normal',english:star,chinese:{situation:'虚构课程背景',task:'虚构任务',action:'虚构个人行动',result:'虚构反馈'},tags:['ownership'],projects:[]});
test('owner story commands preserve a required experience label/privacy choice and reject forged status, evidence, review and metadata',()=>{
 const body=story(),r=parseCareerLibraryCommand('story','create',body);assert(Object.isFrozen(r.english));assert(Object.isFrozen(r.projects));for(const patch of [{status:'confirmed'},{source:'model'},{mentorReview:{reviewerId:randomUUID()}},{confirmedAt:'2026-10-08T00:00:00.000Z'},{sensitivity:''},{tags:['ownership','ownership']},{projects:[{id:randomUUID(),revision:0}]},{english:{...star,metric:100}}])assert.throws(()=>parseCareerLibraryCommand('story','create',{...body,...patch}));
 assert.throws(()=>parseCareerLibraryCommand('story','withdraw',{operationId:randomUUID(),expectedRevision:1}));const malicious={...body};Object.defineProperty(malicious,'title',{enumerable:true,get(){throw Error('Must not execute getters');}});assert.throws(()=>parseCareerLibraryCommand('story','create',malicious));
});
test('a confirmed project/story must bind its actual confirmation revision and time; partial STAR remains a draft',()=>{
 const input=story(),{operationId,expectedRevision,...fields}=input,id=randomUUID(),ownerId=randomUUID(),at='2026-10-08T00:00:00.000Z',base={...fields,id,ownerId,source:'user_entered',revision:2,createdAt:at,updatedAt:at,lastOperationId:operationId,confirmedAt:at,confirmedRevision:2,status:'confirmed'};assert.equal(parseCareerStory(base).status,'confirmed');for(const patch of [{confirmedRevision:1},{confirmedAt:null},{english:{...star,result:''}}])assert.throws(()=>parseCareerStory({...base,...patch}));
 const {english,chinese,tags,projects,status,...common}=base;const project={...common,kind:'project',subjectId:id,referenceId:'career-project:'+id+':2',occurredAt:at,context:'Fictional context',contribution:'Fictional personal work',outcome:'',state:'active',verification:'user_confirmed'};assert.equal(parseCareerProject(project).verification,'user_confirmed');for(const patch of [{verification:'mentor_reviewed'},{subjectId:randomUUID()},{referenceId:'fake-receipt'},{confirmedRevision:1}])assert.throws(()=>parseCareerProject({...project,...patch}));
});
