import { test } from 'node:test';import assert from 'node:assert/strict';import { randomUUID } from 'node:crypto';
import { parseManualJobCommand,parseManualJob,canonicalManualJobUrl,manualJobsDuplicate } from '../src/manual-jobs.ts';
const input=()=>({operationId:randomUUID(),expectedRevision:0,employer:'Fictional Company',title:'Fictional Analyst',canonicalUrl:'https://example.invalid/jobs/1?utm_source=synthetic#text',roleFamily:'da',location:'Fictional City',deadlineAt:null,deadlineTimeZone:null,privateNote:'Fictional private note',jobText:'Fictional analytics role. We sponsor candidates.'});
test('manual job commands reject fabricated observation/model metadata, unsafe URLs, ill-defined time zones and accessor data',()=>{
 const body=input(),command=parseManualJobCommand('create',body);assert.equal(command.canonicalUrl,'https://example.invalid/jobs/1');assert.equal(command.allowDuplicate,false);assert(Object.isFrozen(command));
 for(const patch of [{source:'greenhouse'},{state:'observed_open'},{sponsorship:'explicit_yes'},{ownerId:randomUUID()},{checkedAt:'2026-10-08T00:00:00.000Z'},{jobText:'\u0000'},{canonicalUrl:'javascript:alert(1)'},{canonicalUrl:'https://user:secret@example.invalid/'},{deadlineAt:'2026-10-09T12:00:00.000Z',deadlineTimeZone:'Fictional/Zone'},{deadlineTimeZone:'UTC'},{allowDuplicate:'yes'}])assert.throws(()=>parseManualJobCommand('create',{...body,...patch}));
 const malicious={...body};Object.defineProperty(malicious,'title',{enumerable:true,get(){throw Error('Accessor should not execute');}});assert.throws(()=>parseManualJobCommand('create',malicious));
});
test('evidence must exactly address the stored source; source state and registration time cannot be forged',()=>{
 const c=parseManualJobCommand('create',input()),{operationId,expectedRevision,allowDuplicate,...data}=c,id=randomUUID(),ownerId=randomUUID(),observedAt='2026-10-08T00:00:00.000Z';const quote='We sponsor candidates.',start=data.jobText!.indexOf(quote),job={...data,id,ownerId,sourceId:id,source:'manual',state:'unknown',observedAt,checkedAt:observedAt,revision:1,lastOperationId:operationId,sponsorship:'explicit_yes',sponsorshipEvidence:[{text:quote,start,end:start+quote.length,status:'explicit_yes'}],evidenceOverflow:false,ruleRevision:1};assert.equal(parseManualJob(job).sponsorshipEvidence[0].text,quote);
 for(const patch of [{state:'observed_open'},{source:'lever'},{checkedAt:'2026-10-09T00:00:00.000Z'},{sponsorshipEvidence:[{text:'Fake sponsor guarantee',start,end:start+quote.length,status:'explicit_yes'}]}])assert.throws(()=>parseManualJob({...job,...patch}));
 assert(manualJobsDuplicate({canonicalUrl:'',employer:'Ｆｉｃｔｉｏｎａｌ Company',title:'Fictional  Analyst'},{canonicalUrl:'',employer:'fictional company',title:'fictional analyst'}));assert.equal(canonicalManualJobUrl(''),'');
});
