import {connectedFillView} from '../features/autofill/view';
import { C, PRIMARY_BG, PRIMARY_SHADOW } from '../design/palette';
import type { ViewContext } from './view-context';
import type { ChatMessage, CandidateCard, Entitlement, ProfileField, UploadState } from '../state/types';

export function shortView(ctx: ViewContext) {
    const S = ctx.state, F = ctx.data; const ids = S.deck.selected; const locked = ids.some(id => S.prep[id] === 'ready' || S.prep[id] === 'preparing');
    const versions = F.resumeVersions.map(v => { const on = v.id === S.resumeId; return { id: v.id, label: v.label, note: S.reads ? ctx.t('{v0} · 交付权限需在申请时验证', { v0: ctx.t(v.current ? '当前版本' : '历史版本') }) : v.note, border: on ? C.steel : C.line, bg: on ? '#F7FAFD' : '#fff', ring: on ? C.ink : '#C9D2DF', dot: on ? C.ink : 'transparent', tag: v.kind === 'generated' ? ctx.t("系统生成") : v.current ? ctx.t("已有 · 当前") : ctx.t("已有 · 历史"), tagBg: v.kind === 'generated' ? C.lilac : C.mint, tagColor: v.kind === 'generated' ? '#3B4762' : C.green }; });
    const items = ids.map(id => { const j = ctx.job(id); const st = S.prep[id]; const L = S.letters[id]; const req = ctx.letterReq(id); return { id, title: j.title, company: j.company, location: j.location, initial: j.company[0], markBg: ctx.markBg(id), removable: !st, openable: st === 'ready', retryable: st === 'failed', status: st === 'ready' ? ctx.t("READY · 申请任务已就绪") : st === 'failed' ? ctx.t("准备失败 · 可以重试") : st === 'preparing' ? ctx.t("正在准备…") : ctx.t("待你确认准备"), statusColor: st === 'ready' ? C.green : st === 'failed' ? '#B4483A' : C.muted, statusDot: st === 'ready' ? C.green : st === 'failed' ? C.coral : '#C9D2DF', letterLabel: L ? (L.status === 'kept' ? ctx.t("求职信 · 已保留草稿") : ctx.t("求职信 · 候选草稿")) : req === 'REQUIRED' ? ctx.t("求职信 · 该岗位要求") : req === 'NOT_REQUIRED' ? ctx.t("求职信 · 未要求（可选）") : ctx.t("求职信 · 是否需要未知") }; });
    const anyReady = ids.some(id => S.prep[id] === 'ready'); const allDone = ids.length && ids.every(id => S.prep[id] === 'ready' || S.prep[id] === 'failed');
    const gen = ctx.resume().kind === 'generated';
    if(S.commerceEnabled){
      const M=S.materials,replan=(id:string)=>M?.preparations[id]?.status==='FAILED'&&M.preparations[id]?.failureCode==='SOURCE_CHANGED',working=!!M?.busy||!!M?.loading,accepted=Object.keys(M?.preparations??{}).length>0;
      const connectedVersions=(M?.choices??[]).map(v=>({id:v.id,label:v.plan.mode==='GENERATE_FOR_JOB'?ctx.t('为岗位生成新版 · {v0}',{v0:v.label}):v.label,note:v.plan.mode==='USE_EXISTING'?ctx.t("沿用你选的已有版本，不会偷换"):ctx.t("每个岗位生成独立新版"),
        border:v.id===M?.choice?C.steel:C.line,bg:'#fff',ring:v.id===M?.choice?C.ink:'#C9D2DF',dot:v.id===M?.choice?C.ink:'transparent',
        tag:ctx.t(v.plan.mode==='USE_EXISTING'?"已有 · 当前":"系统生成"),tagBg:C.mint,tagColor:C.green}));
      return {connected:true,moreSaved:!!S.commerce?.savedCursor,loading:working,count:ids.length,title:ctx.t("把心动，变成下一步。"),sub:ctx.t("先确认这轮使用的简历，再为这些岗位准备申请任务。"),empty:!ids.length,hasItems:!!ids.length,
        versions:connectedVersions,locked:working,planNote:ids.some(replan)?ctx.t("素材已变化，请重新选择并准备。"):accepted?ctx.t("每岗材料已锁定，重试沿用原选择"):ctx.t("请明确选择一份简历或生成方式。"),
        items:items.map(item=>({...item,openable:!working&&M?.preparations[item.id]?.status==='READY'&&!!M.preparations[item.id]?.missionId&&!!M.preparations[item.id]?.resumeVersionId,retryable:!working&&!!M?.preparations[item.id]?.retryable,removable:!M?.preparations[item.id],
          status:replan(item.id)?ctx.t("素材已变化，请重新选择并准备。"):M?.preparations[item.id]?.status==='FAILED'&&!M.preparations[item.id]?.retryable?ctx.t("准备失败 · 当前不可重试"):M?.preparations[item.id]?item.status:ctx.t("待你确认准备"),letterLabel:ctx.t("求职信草稿")})),
        primaryAct:working?'materials-refresh':ids.some(id=>!M?.preparations[id]||replan(id))?'prepare':'materials-refresh',
        primaryLabel:ctx.t(working?'正在准备…':ids.some(id=>!M?.preparations[id]||replan(id))?'确认并准备材料':'刷新准备状态'),
        primaryBg:PRIMARY_BG,primaryColor:'#fff',primaryBorder:'transparent',primaryShadow:PRIMARY_SHADOW,
        foot:ctx.t("准备会创建申请任务。填写与提交仍需你另行操作。")};
    }
    return { connected:false,moreSaved:false,loading:false,count: ids.length, title: allDone ? ctx.t("申请材料已准备好。") : ctx.t("把心动，变成下一步。"), sub: allDone ? ctx.t("逐个打开岗位申请页，检查后开始填写。") : ctx.t("先确认这轮使用的简历，再为这些岗位准备申请任务。"), empty: !ids.length, hasItems: !!ids.length, versions, locked, planNote: locked ? ctx.t("已按此版本准备 · 更换需重新准备") : gen ? ctx.t("将基于 v3 为每个岗位生成新版") : ctx.t("沿用你选的已有版本，不会偷换"), items, primaryAct: anyReady ? 'discover' : 'prepare', primaryLabel: anyReady ? ctx.t("继续发现机会") : ctx.t("确认，准备 ") + ids.length + ctx.t(" 份申请"), primaryBg: anyReady ? '#fff' : PRIMARY_BG, primaryColor: anyReady ? C.ink : '#fff', primaryBorder: anyReady ? C.line : 'transparent', primaryShadow: anyReady ? '0 1px 2px rgba(10,17,40,.04)' : PRIMARY_SHADOW, foot: anyReady ? ctx.t("示例状态 · 尚未向任何雇主提交") : ctx.t("确认后为每个岗位创建申请任务（预计使用 ") + ids.length + ctx.t(" 次材料准备 · 示例）；每个岗位仍由你主动开始填写。") };
  }

export function prepView(ctx: ViewContext) { const S = ctx.state; const ids = S.deck.selected; return { count: ids.length, resumeLabel: ctx.resume().label, items: ids.map(id => { const j = ctx.job(id); const st = S.prep[id]; return { title: j.title, company: j.company, initial: j.company[0], markBg: ctx.markBg(id), spinning: st === 'preparing', status: st === 'ready' ? '✓ READY' : st === 'failed' ? ctx.t("! 准备失败") : st === 'preparing' ? ctx.t("核对岗位与简历…") : ctx.t("排队中"), color: st === 'ready' ? C.green : st === 'failed' ? '#B4483A' : C.muted }; }) }; }

export function coverView(ctx: ViewContext) {
    const S = ctx.state; const id = S.coverId || S.deck.selected[0] || 'northstar'; const j = ctx.job(id); const L = S.letters[id]; const req = ctx.letterReq(id); const e = ctx.ent('letters');
    const reqMap = { REQUIRED: [ctx.t("该岗位要求求职信"), C.peach, '#8A5A2B'], NOT_REQUIRED: [ctx.t("该岗位未要求（可选）"), C.grey, C.muted], UNKNOWN: [ctx.t("是否需要 · 未知"), C.lilac, '#3B4762'] }[req];
    const st = L ? L.status : 'none';
    if(S.commerceEnabled)return {connected:true,savedDraft:!!S.materials?.covers[id]?.draft||!!S.materials?.covers[id]?.unavailableReason,title:j.title,company:j.company,initial:j.company[0],markBg:ctx.markBg(id),reqLabel:ctx.t("是否需要 · 未知"),reqBg:C.lilac,reqColor:C.ink,
      stLabel:ctx.t(S.materials?.covers[id]?.unavailableReason?"草稿暂时无法读取，仍可删除。":st==='kept'?"已保存草稿":"可编辑草稿"),stBg:C.grey,stColor:C.muted,quota:ctx.t("生成使用已确认资料；保存不会授权上传。"),
      ask:!L?.text,deferLabel:ctx.t("稍后处理"),askText:ctx.t("岗位没有说明是否需要求职信。由你决定是否生成一封候选草稿。"),
      generating:!!S.materials?.busy,hasDraft:!!S.materials?.covers[id],text:L?.text??'',meta:ctx.t("仅保存当前草稿；修改会替换上次文本。"),keepLabel:ctx.t("保存草稿")};
    return { connected:false,savedDraft:false,title: j.title, company: j.company, initial: j.company[0], markBg: ctx.markBg(id), reqLabel: reqMap[0], reqBg: reqMap[1], reqColor: reqMap[2], stLabel: st === 'kept' ? ctx.t("已保留 · 本地示例草稿") : st === 'draft' ? (L?.edited ? ctx.t("候选草稿 · 已编辑") : ctx.t("候选草稿")) : st === 'generating' ? ctx.t("生成中") : st === 'failed' ? ctx.t("生成失败 · 可以重试") : ctx.t("尚未生成"), stBg: st === 'kept' ? C.mint : C.grey, stColor: st === 'kept' ? C.green : C.muted, quota: e.remaining === undefined ? ctx.t("生成权益暂不可用") : e.remaining === null ? ctx.t("生成不限量（示例）") : ctx.t("生成 · 剩余 ") + e.remaining + ctx.t(" 封（示例）"), ask: st === 'none' || st === 'failed', deferLabel: req === 'REQUIRED' ? ctx.t("稍后处理") : ctx.t("这个岗位不需要"), askText: st === 'failed' ? ctx.t("生成暂时失败，可以重试；已有资料仍然保留。") : req === 'REQUIRED' ? ctx.t("该岗位要求求职信。可以先生成候选草稿，核对与编辑后再保留。") : req === 'NOT_REQUIRED' ? ctx.t("这个岗位没有要求求职信。不生成也可以正常准备申请；需要的话，我也可以写一封。") : ctx.t("岗位没有说明是否需要求职信。由你决定是否生成一封候选草稿。"), generating: st === 'generating', hasDraft: st === 'draft' || st === 'kept', text: L ? L.text : '', meta: ctx.t("基于 ") + j.company + ' · ' + j.title + ctx.t(" 的 JD 与已确认资料 · 可编辑"), keepLabel: st === 'kept' ? ctx.t("已保留 · 更新本地草稿") : ctx.t("保留这份草稿（本地示例）") };
  }

export function fillView(ctx: ViewContext) {
    if(ctx.state.commerceEnabled)return connectedFillView(ctx);
    const S = ctx.state, F = ctx.data; const id = S.fillId || S.deck.selected[0] || 'northstar'; const j = ctx.job(id); const run = S.run; const rows = run.rows.length ? run.rows : F.runRows.map(r => Object.assign({}, r, { state: 'pending' as const })); const p = S.profile;
    const val: Record<string, string> = { name: p.name, email: p.email, phone: p.phone, city: p.city, links: ctx.t("linkedin.example/mia（页面已有）"), resume: ctx.resume().label + '.pdf', workAuth: ctx.t("需要你本人回答"), sign: ctx.t("网站要求本人确认") };
    const rowsV = rows.map(r => { const s = r.state; const map = { pending: { mark: '', iconBg: C.grey, iconColor: C.faint, status: ctx.t("待填写"), statusColor: C.faint, bg: '#fff', weight: 500 }, active: { mark: '', iconBg: C.ice, iconColor: C.ink, status: ctx.t("正在填写…"), statusColor: C.ink, bg: '#F7FAFD', weight: 600 }, filled: { mark: '✓', iconBg: C.mint, iconColor: C.green, status: ctx.t("已写入并核对"), statusColor: C.green, bg: '#fff', weight: 600 }, kept: { mark: '=', iconBg: C.ice, iconColor: C.ink, status: ctx.t("保留你已有内容"), statusColor: C.ink2, bg: '#fff', weight: 500 }, manual: { mark: '!', iconBg: C.peach, iconColor: '#B86A2B', status: ctx.t("需要你本人完成"), statusColor: '#B86A2B', bg: '#fff', weight: 600 }, failed: { mark: '×', iconBg: C.rose, iconColor: '#B4483A', status: ctx.t("填写失败 · 页面可能已改变"), statusColor: '#B4483A', bg: '#fff', weight: 600 } }[s]; return Object.assign({ key: r.key, label: r.label, sub: val[r.key] || r.source, spinning: s === 'active', notSpinning: s !== 'active' }, map, { statusWeight: map.weight }); });
    const filled = rows.filter(r => r.state === 'filled').length, kept = rows.filter(r => r.state === 'kept').length, manual = rows.filter(r => r.state === 'manual').length, failed = rows.filter(r => r.state === 'failed').length;
    const done = run.status === 'done', paused = run.status === 'paused';
    return { showStop:false,showOpenTarget:false,pageLabel:ctx.t('当前申请页'),title: j.title, company: j.company, initial: j.company[0], markBg: ctx.markBg(id), resumeLabel: ctx.resume().label, stateLabel: run.status === 'idle' ? ctx.t("本页将使用的资料 · 8 个必填项") : run.status === 'running' ? ctx.t("正在逐项填写并读回核对") : paused ? ctx.t("已暂停 · 页面发生变化") : ctx.t("本次填写结果"), progress: run.status === 'idle' ? '0 / 8' : (filled + kept) + ' / 8', rows: rowsV, showSummary: done || paused, summaryBg: paused ? C.rose : C.peach, summaryTitle: paused ? ctx.t("填写已暂停") : filled + ctx.t(" 项已填写 · ") + kept + ctx.t(" 项保留 · ") + manual + ctx.t(" 项需你完成"), summaryText: paused ? ctx.t("已写入的 ") + (filled + kept) + ctx.t(" 项保留；第 ") + (filled + kept + 1) + ctx.t(" 项之后未继续。请重新核对页面后再决定是否继续。") : ctx.t("工作授权问题与信息确认签名需要你在网站上亲自完成。请核对已填写内容，再由你点击网站的 Submit。进度不会凑成 100%。"), showStart: !done && !paused, showDone: done || paused, running: run.status === 'running', startLabel: run.status === 'running' ? ctx.t("ArgoLand.AI 正在填写…") : ctx.t("Autofill · 自动填写"), startNote: run.status === 'running' ? ctx.t("每一项写入后读回核对，才会出现 ✓") : ctx.t("开始前会告诉你将使用哪些资料；只在这个岗位与申请页范围内填写。") };
  }
